-- 1. Xóa dữ liệu cũ & Reset ID
ALTER TABLE [dbo].[Products] NOCHECK CONSTRAINT ALL;
DELETE FROM [dbo].[OrderDetails];
DELETE FROM [dbo].[Products];
DBCC CHECKIDENT ('[dbo].[Products]', RESEED, 0);
GO

-- 2. Bơm FULL 168 sản phẩm (Đã nén Description để không bị quá tải)
INSERT INTO Products (ProductName, Price, StockQuantity, Description, ImageURL, CategoryID, Status, RAM, ROM, Color) VALUES
(N'Masstel IZI 10 4G Type-C',400000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342939/masstel-izi-10-xanh-600x600.jpg',1,1,NULL,NULL,N'Xanh Dương'),
(N'Masstel IZI 10 4G',400000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/265311/masstel-izi-10-4g-xanh-thumb-600x600.jpg',1,1,NULL,NULL,N'Xanh Dương'),
(N'Mobell M179',410000,50,N'Hàng chính hãng TGDD','https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/42/354325/mobell-m179-red-thumb-638941821177855485-600x600.jpg',1,1,NULL,NULL,N'Đỏ'),
(N'Mobell M239 4G',430000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/284122/mobell-m239-do-thumb-1-600x600.jpg',1,1,NULL,NULL,N'Đỏ'),
(N'Masstel IZI T6 4G',520000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/322877/masstel-izi-t6-green-thumb-600x600.jpg',1,1,NULL,NULL,N'Xanh lá'),
(N'Mobell M331 4G',540000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/314697/mobell-m331-thumb-xanh-1-600x600.jpg',1,1,NULL,NULL,N'Xanh'),
(N'Mobell F209 4G',610000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/299998/mobell-f209-gold-600x600.jpg',1,1,NULL,NULL,N'Vàng'),
(N'Masstel Fami 50 4G',620000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/323546/masstel-fami-50-green-thumb-600x600.jpg',1,1,NULL,NULL,N'Xanh lá'),
(N'Nokia HMD 105 4G',640000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/329676/nokia-hmd-105-4g-pink-thumb-600x600.jpg',1,1,NULL,NULL,N'Hồng'),
(N'Nokia 105 4G Pro',690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/311033/nokia-105-4g-den-thumb-600x600.jpg',1,1,NULL,NULL,N'Đen'),
(N'Mobell M539 4G',690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/288630/mobell-m539-do-thumb-600x600.jpg',1,1,NULL,NULL,N'Đỏ'),
(N'Masstel Fami 60S 4G',720000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/322876/masstel-fami-60s-blue-thumb-600x600.jpg',1,1,NULL,NULL,N'Xanh Dương'),
(N'Mobell F309 4G',750000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/304608/mobell-f309-trang-thumb-600x600.jpg',1,1,NULL,NULL,N'Vàng'),
(N'Nokia 110 4G Pro',780000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/311034/nokia-110-4g-xanh-thumb-600x600.jpg',1,1,NULL,NULL,N'Xanh'),
(N'Mobell Rock 7',890000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/338026/mobell-rock-7-green-thumb-600x600.jpg',1,1,NULL,NULL,N'Xanh lá'),
(N'Nokia 220 4G',980000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/207956/nokia-220-4g-cam-thumb-600x600.jpg',1,1,NULL,NULL,N'Cam'),
(N'định vị trẻ em Masstel Alfa 5',990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342910/masstel-alfa-5-vang-dong-thumb-600x600.jpg',1,1,NULL,NULL,NULL),
(N'Nokia 3210 4G',1490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/326477/nokia-3210-4g-yellow-thumb-600x600.jpg',1,1,NULL,NULL,N'Vàng'),
(N'HONOR Play 10 3GB/64GB',1990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/358698/honor-play-10-3gb-64gb-xanh-thumb-600x600.jpg',1,1,N'3GB',N'64GB',NULL),
(N'Tecno Spark Go 2 3GB/64GB',1990000,50,N'Hàng chính hãng TGDD','https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/42/341837/tecno-spark-go-2-xanh-thumb-638899027806878098-600x600.jpg',1,1,N'3GB',N'64GB',N'Đen'),
(N'Xiaomi Redmi A5 3GB/64GB',2440000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/335917/xiaomi-redmi-a5-blue-thumb-600x600.jpg',1,1,N'3GB',N'64GB',NULL),
(N'realme Note 60x 3GB/64GB',2450000,50,N'Hàng chính hãng TGDD','https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/42/333280/realme-note-60x-xanh-thumb-638702210952165468-600x600.jpg',1,1,N'3GB',N'64GB',N'Đen'),
(N'Nubia A36 4GB/64GB',2490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/361630/nubia-a36-4gb-64gb-vang-thumb-600x600.jpg',1,1,N'4GB',N'64GB',NULL),
(N'HONOR X5b Plus 4GB/128GB',2490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/333770/honor-x5b-plus-blue-thumb-600x600.jpg',1,1,N'4GB',N'128GB',NULL),
(N'Samsung Galaxy A07 4GB/64GB',2690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/341802/samsung-galaxy-a07-violet-thumb-600x600.jpg',1,1,N'4GB',N'64GB',NULL),
(N'Tecno Spark 40C 4GB/128GB',2590000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/359425/tecno-spark-40c-4gb-128gb-trang-thumb-600x600.jpg',1,1,N'4GB',N'128GB',N'Xám'),
(N'Masstel S9 6GB/256GB',2740000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/336409/masstel-s9-gold-thumb-600x600.jpg',1,1,N'6GB',N'256GB',NULL),
(N'Samsung Galaxy A06 4GB/64GB',2740000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/328752/samsung-galaxy-a06-green-thumbn-600x600.jpg',1,1,N'4GB',N'64GB',N'Xanh lá'),
(N'HONOR X5c 4GB/64GB',2890000,50,N'Hàng chính hãng TGDD',NULL,1,1,N'4GB',N'64GB',N'Đen'),
(N'Motorola G06 POWER 4GB/128GB',2990000,50,N'Hàng chính hãng TGDD',NULL,1,1,N'4GB',N'128GB',N'Nâu nhạt'),
(N'realme Note 70 4GB/64GB',2990000,50,N'Hàng chính hãng TGDD','https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/42/340260/realme-note-70-4gb-64gb-160725-095001-095-600x600.jpg',1,1,N'4GB',N'64GB',NULL),
(N'HONOR X5c Plus 4GB/64GB',3090000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/358691/honor-x5c-plus-4gb-64gb-den-thumb-600x600.jpg',1,1,N'4GB',N'64GB',NULL),
(N'vivo Y03 4GB/128GB',3140000,50,N'Hàng chính hãng TGDD',NULL,1,1,N'4GB',N'128GB',N'Xanh'),
(N'Samsung Galaxy A06 5G 6GB/128GB',3400000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/335234/samsung-galaxy-a06-5g-black-thumbn-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'OPPO A5i 4GB/64GB',3290000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/340259/oppo-a5i-red-thumb-600x600.jpg',1,1,N'4GB',N'64GB',NULL),
(N'vivo Y04 4GB/128GB',3330000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/335228/vivo-y04-green-thumb-600x600.jpg',1,1,N'4GB',N'128GB',NULL),
(N'realme Note 60 4GB/128GB',3330000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/329329/realme-note-60-blue-thumb-600x600.jpg',1,1,N'4GB',N'128GB',N'Xanh'),
(N'Xiaomi Redmi 13x 6GB/128GB',3720000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/335755/xiaomi-redmi-13x-blue-thumbn-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'OPPO A5x 4GB/64GB',3630000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/337846/oppo-a5x-4gb-64gb-thumb-600x600.jpg',1,1,N'4GB',N'64GB',NULL),
(N'Motorola G35 5G 4GB/128GB',3690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/358048/motorola-moto-g35-5g-4gb-128gb-green-thumb2-600x600.jpg',1,1,N'4GB',N'128GB',N'Xanh lá'),
(N'Xiaomi Redmi 15C 6GB/128GB',3690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/346265/xiaomi-redmi-15c-6gb-128gb-xanh-la-thumb-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'realme C71 4GB/128GB',3820000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/337741/realme-c71-trang-thumb-600x600.jpg',1,1,N'4GB',N'128GB',NULL),
(N'OPPO A3x 6GB/128GB',4110000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/328452/oppo-a3x-red-thumb-600x600.jpg',1,1,N'6GB',N'128GB',N'Đỏ'),
(N'OPPO A6x 4GB/64GB',3990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360244/oppo-a6x-4gb-64gb-tim-titan-thumb-1-600x600.jpg',1,1,N'4GB',N'64GB',NULL),
(N'OPPO A6t 4GB/64GB',3990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/361191/oppo-a6t-4gb-64gb-xanh-thumb-600x600.jpg',1,1,N'4GB',N'64GB',NULL),
(N'HONOR X6c 6GB/128GB',3990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/340220/honor-x6c-6gb-128gb-xanh-thumb-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'realme C75x 8GB/128GB',4200000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/335307/realme-c75x-pink-thumbn-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'Samsung Galaxy A17 4GB/128GB',4290000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/341797/samsung-galaxy-a17-lte-xam-thumb-600x600.jpg',1,1,N'4GB',N'128GB',NULL),
(N'Xiaomi Redmi 15 6GB/128GB',4290000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/341272/xiaomi-redmi-15-tim-thumbnew-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'HONOR X7c 8GB/256GB',4300000,50,N'Hàng chính hãng TGDD',NULL,1,1,N'8GB',N'256GB',N'Đen'),
(N'Samsung Galaxy A07 5G 4GB/128GB',4390000,50,N'Hàng chính hãng TGDD',NULL,1,1,N'4GB',N'128GB',N'Tím'),
(N'Samsung Galaxy A16 8GB/128GB',4400000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/331207/samsung-galaxy-a16-black-thumb-1-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'OPPO A3 8GB/128GB',4700000,50,N'Hàng chính hãng TGDD',NULL,1,1,N'8GB',N'128GB',N'Đen'),
(N'Xiaomi Redmi Note 14 8GB/128GB',4800000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/333147/xiaomi-redmi-note-14-green-thumbnew-600x600.jpg',1,1,N'8GB',N'128GB',N'Xanh lá'),
(N'Tecno Pova 7 8GB/256GB',4990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/362632/tecno-pova-7-8gb-256gb-den-thumb-1-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'vivo Y19s Pro 8GB/128GB',5000000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/338918/vivo-y19s-pro-den-thumb-1-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'HONOR X8c 8GB/256GB',5000000,50,N'Hàng chính hãng TGDD','https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/42/335792/honor-x8c-green-thumb-638778940941716593-600x600.jpg',1,1,N'8GB',N'256GB',N'256GB'),
(N'realme C75 8GB/256GB',5180000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/332235/realme-c75-8gb-256gb-thumb-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'Xiaomi Redmi 15 5G 4GB/128GB',5190000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/359776/xiaomi-redmi-15-5g-4gb-128gb-xanh-thumb-600x600.jpg',1,1,N'4GB',N'128GB',NULL),
(N'Honor X7d 8GB/128GB',5490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/362971/honor-x7d-8gb-128gb-xanh-thumb-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'Xiaomi Redmi Note 14 Pro 8GB/256GB',5650000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/320730/xiaomi-redmi-note-14-pro-xanh-thumbnew-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'OPPO A60 8GB/256GB',5680000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/323544/oppo-a60-blue-thumb-1-600x600.jpg',1,1,N'8GB',N'256GB',N'Xanh dương nhạt'),
(N'Xiaomi Redmi Note 15 6GB/128GB',5690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360302/xiaomi-redmi-note-15-thumb-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'Samsung Galaxy A16 5G 8GB/256GB',5700000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/331204/samsung-galaxy-a16-5g-gold-thumb-600x600.jpg',1,1,N'8GB',N'256GB',N'Vàng'),
(N'vivo Y29 8GB/128GB',5880000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/334226/vivo-y29-trang-thumb-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'Samsung Galaxy A17 5G 8GB/128GB',5890000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/341688/galaxy-a17-5g-gray-thumbai-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'HONOR X8b 8GB/512GB',6060000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/324893/honor-x8b-green-thumb-1-600x600.jpg',1,1,N'8GB',N'512GB',NULL),
(N'Samsung Galaxy A26 5G 6GB/128GB',6070000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/335915/samsung-galaxy-a26-5g-black-thumbn-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'realme C85 8GB/128GB',6090000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360344/realme-c85-8gb-128gb-xanh-thumb-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'OPPO A5 Pro 8GB/256GB',6170000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/334323/oppo-a5-pro-blue-thumbai-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'HONOR X9c Smart 5G 12GB/256GB',6650000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/333480/honor-x9c-smart-xanh-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'vivo Y21d 6GB/128GB',6290000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/358669/vivo-y21d-purple-thumb-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'OPPO A5 8GB/128GB',6290000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/341378/oppo-a5-8gb-128gb-xanh-thumb-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'OPPO A5i Pro 8GB/128GB',6290000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/340255/oppo-a5i-pro-white-thumb-600x600.jpg',1,1,N'8GB',N'128GB',N'Trắng'),
(N'vivo Y28 8GB/256GB',6380000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/326023/vivo-y28-xanh-thumbn-600x600.jpg',1,1,N'8GB',N'256GB',N'Xanh đen'),
(N'Honor X7d 5G 8GB/256GB',6690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/358026/honor-x7d-5g-bac-thumb-600x600.jpg',1,1,N'8GB',N'256GB',N'Bạc'),
(N'Xiaomi Redmi Note 14 5G 8GB/256GB',6490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/335583/xiaomi-redmi-note-14-5g-purple-thumbai-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'realme C85 Pro 8GB/128GB',6590000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/357832/realme-c85-pro-purple-thumb-1-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'Motorola G57 Power 5G 8GB/128GB',6690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/362373/motorola-g57-power-5g-8gb-128gb-xanh-bac-ha-thumb-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'Motorola G86 POWER 5G 8GB/128GB',6790000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/358225/motorola-moto-g86-5g-8gb-128gb-xam-thumb-600x600.jpg',1,1,N'8GB',N'128GB',N'Xanh tím'),
(N'vivo V40 Lite 8GB/256GB',6840000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/329959/vivo-v40-lite-tim-thumb-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'Xiaomi Redmi Note 15 5G 6GB/128GB',6990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360310/xiaomi-redmi-note-15-5g-thumb-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'vivo Y39 5G 8GB/128GB',7160000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/339180/vivo-y39-5g-thumb-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'Xiaomi Redmi Note 14 Pro 5G 8GB/256GB',7220000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/332938/xiaomi-redmi-note-14-pro-5g-xanh-thumbai-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'OPPO Reno13 F 5G 8GB/256GB',7310000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/332936/oppo-reno13-f-purple-thumbnew-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'realme C85 5G 8GB/128GB',7590000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/362760/realme-c85-green-thumb-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'HONOR 400 Lite 12GB/256GB',7680000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/339245/honor-400-lite-xam-thumb-600x600.jpg',1,1,N'12GB',N'256GB',N'Xám'),
(N'vivo V50 Lite 8GB/256GB',7830000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/336702/vivo-v50-lite-tim-thumbai-600x600.jpg',1,1,N'8GB',N'256GB',N'Tím'),
(N'HONOR X8d 8GB/128GB',8090000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/362919/honor-x8d-8gb-128gb-xanh-thumb-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'vivo Y31d 6GB/128GB',8090000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360671/vivo-y31d-6gb-128gb-trang-thumb-600x600.jpg',1,1,N'6GB',N'128GB',NULL),
(N'OPPO A6 8GB/128GB',8290000,50,N'Hàng chính hãng TGDD',NULL,1,1,N'8GB',N'128GB',NULL),
(N'OPPO A6 Pro 8GB/128GB',8290000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/344651/oppo-a6-pro-4g-pink-thumbai-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'vivo V50 Lite 5G 8GB/256GB',8310000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/336408/vivo-v50-lite-gold-5g-thumbai-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'realme 15T 5G 8GB/256GB',8490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/343063/realme-15t-sliver-thumb-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'Xiaomi Redmi Note 15 Pro 8GB/256GB',8690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360307/xiaomi-redmi-note-15-pro-thumb-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'Motorola Edge 60 Fusion 5G 8GB/256GB',8690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/358224/motorola-edge-60-fusion-8gb-256gb-blue-thumb-600x600.jpg',1,1,N'8GB',N'256GB',N'Xanh Nước Biển'),
(N'realme 14 5G 12GB/256GB',8800000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/336623/realme-14-5g-xam-thumb-600x600.jpg',1,1,N'12GB',N'256GB',N'Xám'),
(N'OPPO Reno14 F 5G 8GB/256GB Hồng',10100000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/339624/oppo-reno14-f-5g-8gb-256gb-hong-thumb-600x600.jpg',1,1,N'8GB',N'256GB',N'Hồng'),
(N'Xiaomi Redmi Note 14 Pro+ 5G 12GB/512GB',9160000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/337713/xiaomi-redmi-note-14-pro-plus-5g-gold-thumb-600x600.jpg',1,1,N'12GB',N'512GB',N'Vàng'),
(N'Samsung Galaxy A36 5G 12GB/256GB',9210000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/334930/samsung-galaxy-a36-5g-green-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'realme 15 5G 12GB/256GB',9990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/343066/realme-15-5g-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'Xiaomi Redmi Note 15 Pro 5G 8GB/256GB',10190000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360312/xiaomi-redmi-note-15-pro-5g-thumb-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'vivo V30e 5G 12GB/256GB',10300000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/325136/vivo-v30e-nau-thumb-1-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'Samsung Galaxy A56 5G 12GB/256GB',10780000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/334932/samsung-galaxy-a56-5g-gray-thumb-1-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'vivo V60 Lite 5G 8GB/256GB',10490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/357576/vivo-v60-lite-pink-thumbai-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'HONOR X9d 5G 12GB/256GB',10990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/358683/honor-x9d-5g-12gb-256gb-do-thumb-1-2-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'OPPO A6 Pro 5G 12GB/256GB',10990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/344649/oppo-a6-pro-5g-pink-thumbai-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'OPPO Reno14 F 5G 12GB/256GB',11090000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/339177/oppo-reno14-f-5g-12gb-256gb-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'vivo V40 5G 12GB/256GB',11260000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/331985/vivo-v40-5g-thumb-600x600.jpg',1,1,N'12GB',N'256GB',N'Cam'),
(N'realme 16 5G 8GB/256GB',11490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/361703/realme-16-5g-8gb-256gb-trang-thumb-1-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'OPPO Reno15 F 5G 8GB/256GB',11990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360240/oppo-reno15f-5g-8gb-256gb-hong-thumb-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'HONOR 400 5G 12GB/256GB Đen',11990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/339638/honor-400-5g-12gb-256gb-den-thumb-600x600.jpg',1,1,N'12GB',N'256GB',N'256GB Đen'),
(N'OPPO Reno13 5G 12GB/256GB',12200000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/332934/oppo-reno13-blue-thumbnew-600x600.jpg',1,1,N'12GB',N'256GB',N'Xanh Dương'),
(N'Motorola Edge 70 8GB/256GB',12490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/362374/motorola-edge-70-8gb-256gb-xam-thumb-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'iPhone 13 128GB',12490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/223602/iphone-13-midnight-2-600x600.jpg',1,1,NULL,NULL,N'Đen'),
(N'Xiaomi Redmi Note 15 Pro+ 5G 12GB/256GB',12690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360309/xiaomi-redmi-note-15-pro-plus-5g-thumb-600x600.jpg',1,1,N'12GB',N'256GB',N'Nâu'),
(N'Samsung Galaxy S24 FE 5G 8GB/256GB',12790000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/329785/samsung-galaxy-s24-fe-8gb-256gb-thumb-600x600.jpg',1,1,N'8GB',N'256GB',N'Xanh Dương'),
(N'realme 15 Pro 5G 12GB/256GB',12990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/343067/realme-15t-pro-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'Samsung Galaxy S25 FE 5G 8GB/128GB',13790000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342560/samsung-galaxy-s25-fe-blue-thumbai-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'Xiaomi 15T 5G 12GB/512GB',13990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/344645/xiaomi-15t-12gb-512gb-xam-den-thumb-600x600.jpg',1,1,N'12GB',N'512GB',N'Đen'),
(N'Xiaomi 15T 5G 12GB/256GB',13990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/344644/xiaomi-15t-12gb-256gb-vang-thumb-600x600.jpg',1,1,N'12GB',N'256GB',N'Vàng'),
(N'OPPO Find N3 Flip 5G 12GB/256GB Hồng',13990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/317981/oppo-find-n3-flip-hong-thumb-1-600x600.jpg',1,1,N'12GB',N'256GB',N'Hồng'),
(N'iPhone 14 128GB',13990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/240259/iPhone-14-plus-thumb-xanh-600x600.jpg',1,1,NULL,NULL,NULL),
(N'realme 16 Pro 5G 12GB/256GB',14490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/361707/realme-16-pro-5g-12gb-256gb-tim-thumb-1-600x600.jpg',1,1,N'12GB',N'256GB',N'Tím'),
(N'Samsung Galaxy S24 5G 8GB/256GB',14990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/319665/samsung-galaxy-s24-256gb-5g-thumb-600x600.jpg',1,1,N'8GB',N'256GB',N'Vàng'),
(N'vivo V60 5G 12GB/256GB',15390000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/341625/vivo-v60-5g-xam-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'OPPO Reno15 5G 8GB/256GB',15990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360238/oppo-reno15-5g-8gb-256gb-xanh-thumb-600x600.jpg',1,1,N'8GB',N'256GB',NULL),
(N'iPhone 16e 128GB',15990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/334864/iphone-16e-den-thumb-600x600.jpg',1,1,NULL,NULL,NULL),
(N'OPPO Reno14 5G 12GB/512GB',16690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/339174/oppo-reno14-5g-512gb-thumb-600x600.jpg',1,1,N'12GB',N'512GB',N'512GB'),
(N'Samsung Galaxy S25 5G 12GB/256GB',17690000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/333363/samsung-galaxy-s25-green-thumbai-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'iPhone 17e 256GB',17990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342692/iphone-17e-256gb-hong-thumb-600x600.jpg',1,1,NULL,NULL,NULL),
(N'iPhone 15 128GB',18090000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/281570/iphone-15-xanh-thumb-600x600.jpg',1,1,NULL,NULL,NULL),
(N'Xiaomi 15T Pro 5G 12GB/256GB',18490000,50,N'Hàng chính hãng TGDD',NULL,1,1,N'12GB',N'256GB',N'Vàng'),
(N'Samsung Galaxy Z Flip7 FE 5G 8GB/128GB',18490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/338741/samsung-galaxy-z-flip7-fe-black-thumb-600x600.jpg',1,1,N'8GB',N'128GB',NULL),
(N'OPPO Reno15 Pro 5G 12GB/256GB',18990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/360236/oppo-reno15-pro-5g-12gb-256gb-xanh-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'Xiaomi 15T Pro 5G 12GB/512GB',19490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/356739/xiaomi-15t-pro-5g-12gb-512gb-xam-thumb-600x600.jpg',1,1,N'12GB',N'512GB',N'Xám'),
(N'Motorola Razr 60 5G 8GB/256GB',19190000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/2026/03/timerseo/358223.jpg',1,1,N'8GB',N'256GB',NULL),
(N'Samsung Galaxy S25 Edge 5G 12GB/512GB',19490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/2026/03/timerseo/335955.jpg',1,1,N'12GB',N'512GB',NULL),
(N'iPhone 15 Plus 128GB',19990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/303891/iphone-15-plus-128gb-den-thumb-600x600.jpg',1,1,NULL,NULL,N'Đen'),
(N'Xiaomi 15T Pro 5G 12GB/1TB',20490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/356740/xiaomi-15t-pro-5g-12gb-1tb-xanh-thumb-600x600.jpg',1,1,N'12GB',N'1TB',N'Xanh'),
(N'iPhone 16 128GB',21090000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/329135/iphone-16-luu-ly-thumb-600x600.jpg',1,1,NULL,NULL,NULL),
(N'vivo X300 5G 12GB/256GB',21490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/357855/vivo-x300-5g-bac-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'OPPO Find X8 5G 16GB/512GB Hồng',22580000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/2026/03/timerseo/334168.jpg',1,1,N'16GB',N'512GB',N'Hồng'),
(N'Samsung Galaxy S24 Ultra 5G 12GB/256GB',22590000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/307172/samsung-galaxy-s24-ultra-xam-thumb-1-600x600.jpg',1,1,N'12GB',N'256GB',N'Xám'),
(N'Samsung Galaxy S25 Plus 5G 12GB/256GB',22700000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/333364/samsung-galaxy-s25-plus-green-thumbai-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'Motorola Signature 12GB/256GB',22990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/362375/motorola-signature-12gb-256gb-xanh-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'Samsung Galaxy Z Flip7 5G 12GB/256GB',22990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/2026/03/timerseo/338736.jpg',1,1,N'12GB',N'256GB',NULL),
(N'OPPO Find X9 5G 12GB/256GB',22990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/344655/oppo-find-x9-black-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'Xiaomi 17 5G 12GB/256GB',22990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/331327/xiaomi-17-den-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'Samsung Galaxy S26 5G 12GB/256GB',22990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342130/samsung-galaxy-s26-den-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'iPhone 17 256GB',24990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342667/iphone-17-xanh-duong-thumb-2-600x600.jpg',1,1,NULL,NULL,N'Xanh Dương'),
(N'iPhone Air 256GB',24990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342670/iphone-air-vang-thumb-600x600.jpg',1,1,NULL,NULL,N'Vàng'),
(N'iPhone 16 Plus 128GB',25090000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/329145/iphone-16-plus-den-thumb-600x600.jpg',1,1,NULL,NULL,N'Đen'),
(N'OPPO Find N3 5G 16GB/512GB',26990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/314205/oppo-find-n3-vang-thumb-600x600.jpg',1,1,N'16GB',N'512GB',N'Vàng'),
(N'Samsung Galaxy S26+ 5G 12GB/256GB',26990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342132/samsung-galaxy-s26-plus-den-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'Samsung Galaxy S25 Ultra 5G 12GB/256GB',28490000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/333365/samsung-galaxy-s25-ultra-green-thumbai-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'OPPO Find X8 Pro 5G 16GB/512GB',29450000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/2026/03/timerseo/322129.jpg',1,1,N'16GB',N'512GB',N'Đen'),
(N'iPhone 16 Pro Max 256GB',31590000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/329149/iphone-16-pro-max-sa-mac-thumb-1-600x600.jpg',1,1,NULL,NULL,N'Đen'),
(N'vivo X300 Pro 5G 16GB/512GB',31990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/357862/vivo-x300-pro-den-thumb-600x600.jpg',1,1,N'16GB',N'512GB',NULL),
(N'Samsung Galaxy S26 Ultra 5G 12GB/256GB',32990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342134/samsung-galaxy-s26-ultra-den-thumb-600x600.jpg',1,1,N'12GB',N'256GB',NULL),
(N'OPPO Find X9 Pro 5G 16GB/512GB',32990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/344658/oppo-find-x9-pro-black-thumb-600x600.jpg',1,1,N'16GB',N'512GB',NULL),
(N'iPhone 17 Pro 256GB',34790000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342674/iphone-17-pro-tim-thumb-600x600.jpg',1,1,NULL,NULL,N'Tím'),
(N'Xiaomi 17 Ultra 5G 16GB/512GB',36990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/331329/xiaomi-17-ultra-trang-thumb-600x600.jpg',1,1,N'16GB',N'512GB',N'Trắng'),
(N'iPhone 17 Pro Max 256GB',37990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/342679/iphone-17-pro-max-cam-thumb-600x600.jpg',1,1,NULL,NULL,N'Cam'),
(N'iPhone 16 Pro 1TB',39990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/329143/iphone-16-pro-sa-mac-thumb-600x600.jpg',1,1,NULL,N'1TB',N'Đen'),
(N'Samsung Galaxy Z Fold7 5G 12GB/256GB',40990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/2026/03/timerseo/338738.jpg',1,1,N'12GB',N'256GB',NULL),
(N'HONOR Magic V5 5G 16GB/512GB',42990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/344641/honor-magic-v5-black-thumb-600x600.jpg',1,1,N'16GB',N'512GB',NULL),
(N'Xiaomi 17 Ultra 5G Limited Leica 16GB/1TB',44990000,50,N'Hàng chính hãng TGDD','https://cdn.tgdd.vn/Products/Images/42/361312/xiaomi-17-ultra-limited-leica-thumb-600x600.jpg',1,1,N'16GB',N'1TB',NULL);
GO

-- 3. Bật lại kiểm tra khóa
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT ALL;
GO

UPDATE [dbo].[Products] SET [Description] = N'Masstel IZI 10 4G là 1 phiên bản "cục gạch" khác của nhà Masstel có tích hợp 4G mang lại trải nghiệm nghe gọi cực tốt, cùng thiết kế thân thiện dễ dùng, có hỗ trợ khe cắm thẻ nhớ và dung lượng pin tốt, rất đáng lựa chọn.Thiết kế thân thiện, dễ dùn...' WHERE [ProductName] = N'Masstel IZI 10 4G';
UPDATE [dbo].[Products] SET [Description] = N'Đặc điểm nổi bật của Mobell M179Hỗ trợ 4G, đảm bảo kết nối ổn định cho nhu cầu nghe gọi.Pin 1000 mAh, cung cấp thời gian sử dụng kéo dài nhiều ngày.Cổng kết nối Type-C, tiêu chuẩn sạc hiện đại và tiện lợi.Hỗ trợ 2 Nano SIM, linh hoạt trong việc ...' WHERE [ProductName] = N'Mobell M179';
UPDATE [dbo].[Products] SET [Description] = N'Mobell chính thức trình làng điện thoại phổ thông Mobell M239, mang ưu điểm với một thiết kế gọn gàng và màu sắc trẻ trung.Thiết kế đơn giản, cứng cápMobell M239 sở hữu ngoại hình quen thuộc của dòng điện thoại phổ thông, khi sử dụng chất liệu nh...' WHERE [ProductName] = N'Mobell M239 4G';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây (09/2021) hãng Masstel đã cho ra mắt chiếc điện thoại phổ thông Masstel Fami 60S với nhiều tính năng hấp dẫn hỗ trợ cho người lớn tuổi sử dụng dễ dàng hơn, là một món quà cực kỳ ý nghĩa mà bạn có thể dành tặng cho người thân của mình.Hỗ t...' WHERE [ProductName] = N'Masstel Fami 60S 4G';
UPDATE [dbo].[Products] SET [Description] = N'Masstel IZI T6 4G nổi bật với viên pin dung lượng 1800 mAh, thiết kế gọn nhẹ kết hợp công nghệ 4G cho kết nối tốt, đảm bảo quá trình liên lạc không bị gián đoạn. Đây là chiếc điện thoại phổ thông có giá siêu hạt dẻ phù hợp để bạn mua làm máy phụ ...' WHERE [ProductName] = N'Masstel IZI T6 4G';
UPDATE [dbo].[Products] SET [Description] = N'HMD Global gần đây đã ra mắt Nokia 105 4G, một chiếc điện thoại phổ thông mang đến thiết kế tối giản, tập trung vào khả năng nghe gọi và nhắn tin cốt lõi. Đây là một sự lựa chọn tuyệt vời cho những người cần một thiết bị liên lạc đáng tin cậy hoặ...' WHERE [ProductName] = N'Nokia HMD 105 4G';
UPDATE [dbo].[Products] SET [Description] = N'Nokia 105 4G Pro mang đến sự kết hợp hoàn hảo giữa những yếu tố cổ điển và công nghệ 4G tiên tiến, đáp ứng hoàn hảo các nhu cầu cơ bản mà người dùng thường mong đợi từ một chiếc điện thoại phổ thông.Đường nét tinh giản, phong cách cổ điểnNokia 10...' WHERE [ProductName] = N'Nokia 105 4G Pro';
UPDATE [dbo].[Products] SET [Description] = N'Masstel mang đến người dùng mẫu điện thoại Masstel Fami 50 4G (2024), thiết bị không chỉ đáp ứng tốt nhu cầu nghe gọi với chất lượng âm thanh rõ ràng, mà còn được tích hợp nhiều tính năng hữu ích dành cho người lớn tuổi. Kết hợp với thiết kế nhỏ ...' WHERE [ProductName] = N'Masstel Fami 50 4G';
UPDATE [dbo].[Products] SET [Description] = N'Mobell đã bổ sung thêm vào dòng sản phẩm điện thoại phổ thông chiếc Mobell M331 4G, thiết bị đáp ứng các nhu cầu nghe gọi và nhắn tin hàng ngày một cách tốt nhất. Với thiết kế chắc chắn và các tính năng đơn giản nhưng hiệu quả, đây là một lựa chọ...' WHERE [ProductName] = N'Mobell M331 4G';
UPDATE [dbo].[Products] SET [Description] = N'Mobell M539 thuộc dòng điện thoại phổ thông mang trong mình thiết kế cứng cáp cùng đầy đủ các chức năng cơ bản, là lựa chọn phù hợp cho người dùng lớn tuổi cần một thiết bị dễ dùng, đáp ứng tốt nhu cầu nghe gọi và nhắn tin hằng ngày.Màn hình lơn ...' WHERE [ProductName] = N'Mobell M539 4G';
UPDATE [dbo].[Products] SET [Description] = N'Nokia 110 4G Pro là một chiếc điện thoại mang đậm phong cách truyền thống của Nokia, được tích hợp công nghệ mạng 4G, đáp ứng hoàn hảo nhu cầu liên lạc hàng ngày và giải trí cơ bản cho người dùng.Thiết kế bền bỉ, phong cách cổ điểnNokia 110 4G Pr...' WHERE [ProductName] = N'Nokia 110 4G Pro';
UPDATE [dbo].[Products] SET [Description] = N'Nếu bạn là một người dùng chỉ cần một chiếc điện thoại đáp ứng được những nhu cầu cơ bản từ nghe gọi, độ bền cao và lượng pin siêu khủng thì chiếc điện thoại phổ thông Mobell F309 là một thiết bị không thể bỏ qua.Diện mạo trẻ trungMột sản phẩm xu...' WHERE [ProductName] = N'Mobell F309 4G';
UPDATE [dbo].[Products] SET [Description] = N'Mobell F209 là điện thoại phổ thông sở hữu thiết kế nhỏ gọn, bàn phím dễ bấm, tính năng nghe đài FM không cần tai nghe cùng viên pin 1500 mAh bền bỉ. Mẫu máy này mang đến trải nghiệm liên lạc ổn định, rõ ràng và đặc biệt phù hợp làm máy phụ hoặc ...' WHERE [ProductName] = N'Mobell F209 4G';
UPDATE [dbo].[Products] SET [Description] = N'Khám phá chiếc điện thoại Masstel S9 với những tính năng vượt trội, mang đến cho bạn trải nghiệm sử dụng mượt mà và linh hoạt. Không chỉ nổi bật ở một mức giá dễ tiếp cận, chiếc điện thoại này còn được trang bị cấu hình ổn định để đáp ứng mọi nhu...' WHERE [ProductName] = N'Masstel S9 6GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Nokia 3210 4G mang đến một làn gió mới trong thiết kế với hai phiên bản màu sắc rực rỡ và bắt mắt: Vàng và Xanh lam. Không chỉ giữ lại hình dáng đặc trưng quen thuộc của người tiền nhiệm huyền thoại, chiếc điện thoại phổ thông này còn thu hút mọi ...' WHERE [ProductName] = N'Nokia 3210 4G';
UPDATE [dbo].[Products] SET [Description] = N'Đầu năm 2024, hãng Mobell giới thiệu mẫu điện thoại phổ thông mới mang tên Mobell Rock 7. Sản phẩm này nổi bật với thiết kế bền bỉ nhờ bộ khung nhựa cứng cáp, mang lại vẻ ngoài mạnh mẽ và ấn tượng ngay từ cái nhìn đầu tiên. Bên cạnh đó, với viên ...' WHERE [ProductName] = N'Mobell Rock 7';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại Nokia 220 4G được thiết kế lại nhằm mang đến diện mạo mới mẻ và trẻ trung hơn so với các thế hệ trước. Dù được làm mới, sản phẩm vẫn giữ những nét đặc trưng quen thuộc của điện thoại Nokia, khiến những người yêu thích thương hiệu không...' WHERE [ProductName] = N'Nokia 220 4G';
UPDATE [dbo].[Products] SET [Description] = N'Đồng hồ thông minh trẻ em Masstel Alfa 5 Xanh đem đến sự yên tâm cho bố mẹ trong việc theo dõi, bảo vệ an toàn cho con trẻ. Không những thế chiếc đồng hồ thông minh này còn có những chức năng hiện đại như gọi điện rõ nét, chặn số lạ, màn hình mượ...' WHERE [ProductName] = N'định vị trẻ em Masstel Alfa 5';
UPDATE [dbo].[Products] SET [Description] = N'Tecno Spark Go 2 nổi bật với thiết kế phong cách và màn hình 120Hz mượt mà. Pin khủng 5000 mAh cùng nhiều tính năng AI hiện đại giúp tối ưu hóa trải nghiệm hàng ngày.Thiết kế mặt lưng nhám tinh tế và mỏng nhẹTecno Spark Go 2 có độ mỏng chỉ 8 mm, ...' WHERE [ProductName] = N'Tecno Spark Go 2 3GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'HONOR Play 10 tự hào mang đến một trải nghiệm kết nối và sử dụng mượt mà, ấn tượng, lý tưởng cho những người cần một chiếc điện thoại phục vụ công việc và giải trí cơ bản suốt một ngày dài mà không cần sạc liên tục.Pin 5200 mAh sử dụng dài lâuĐượ...' WHERE [ProductName] = N'HONOR Play 10 3GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'Thị trường điện thoại giá rẻ vốn luôn sôi động với sự góp mặt của nhiều thương hiệu lớn. Mới đây, Nubia cũng đã tham gia vào phân khúc này với chiếc Nubia A36. Sản phẩm này được thiết kế hướng tới người dùng phổ thông, mong muốn một thiết bị cấu ...' WHERE [ProductName] = N'Nubia A36 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'Xiaomi Redmi A5 là một lựa chọn đáng cân nhắc trong phân khúc điện thoại giá rẻ, mang đến thiết kế thời trang, hiệu năng ổn định và viên pin lớn. Chiếc smartphone này phù hợp cho những ai tìm kiếm một thiết bị đáp ứng tốt nhu cầu liên lạc, giải t...' WHERE [ProductName] = N'Xiaomi Redmi A5 3GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'HONOR X5b Plus mang đến cho người dùng một trải nghiệm ấn tượng nhờ thiết kế tinh tế, camera 50 MP chụp ảnh rõ nét và dung lượng pin lớn đáp ứng tốt nhu cầu sử dụng suốt cả ngày dài.Chiếc điện thoại này thực sự là một ứng cử viên sáng giá trong p...' WHERE [ProductName] = N'HONOR X5b Plus 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'HONOR X5c là chiếc điện thoại thuộc phân khúc giá rẻ được HONOR cho ra mắt với nhiều ưu điểm hấp dẫn. Từ màn hình sắc nét, cấu hình đủ dùng cho đến thiết kế tối giản nhưng sang trọng, chiếc điện thoại này hứa hẹn sẽ mang đến cho bạn trải nghiệm m...' WHERE [ProductName] = N'HONOR X5c 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'realme Note 60x nổi bật là một chiếc điện thoại phổ thông mạnh mẽ với viên pin 5000 mAh bền bỉ, màn hình 6.74 inch sắc nét và đặc biệt là chuẩn kháng nước bụi IP54. Cùng thiết kế trẻ trung và camera 32 MP bắt trọn khoảnh khắc, thiết bị này chắc c...' WHERE [ProductName] = N'realme Note 60x 3GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung Galaxy A06 mang đến một trải nghiệm vượt trội trong phân khúc giá rẻ. Với những cải tiến nổi bật từ màn hình 6.7 inch rộng rãi, camera chính 50 MP, cho đến thiết kế sang trọng và hiện đại, máy chắc chắn sẽ thu hút sự chú ý của nhiều người...' WHERE [ProductName] = N'Samsung Galaxy A06 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung tiếp tục khẳng định vị thế dẫn đầu ở phân khúc phổ thông với mẫu Galaxy A07. Sở hữu viên pin 5000 mAh cho thời lượng sử dụng bền bỉ, màn hình lớn sắc nét, cùng khả năng vận hành ổn định, đây thực sự là một thiết bị di động rất đáng cân nh...' WHERE [ProductName] = N'Samsung Galaxy A07 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'HONOR mang đến cho người dùng mẫu HONOR X5c Plus, một sản phẩm nằm trong phân khúc giá rẻ nhưng sở hữu nhiều tính năng ấn tượng. Với màn hình lớn sắc nét, cấu hình ổn định và viên pin bền bỉ, đây là lựa chọn hợp lý cho học sinh, sinh viên và nhữn...' WHERE [ProductName] = N'HONOR X5c Plus 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, Motorola đã bổ sung vào phân khúc giá rẻ mẫu điện thoại Moto G06 POWER. Thiết bị thu hút sự chú ý với viên pin cực “khủng”, thiết kế bền bỉ cùng màn hình rõ nét. Đây sẽ là sự lựa chọn hợp lý dành cho học sinh, sinh viên hoặc những người ...' WHERE [ProductName] = N'Motorola G06 POWER 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'realme Note 70 mang đến trải nghiệm bền bỉ với khả năng kháng nước IP64, chống bụi, và bảo vệ linh kiện toàn diện chuẩn ArmorShell. Với màn hình 120Hz mượt mà và pin 5000 mAh hỗ trợ sạc nhanh, sản phẩm hứa hẹn đáp ứng tốt mọi nhu cầu cơ bản với mứ...' WHERE [ProductName] = N'realme Note 70 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'Sự ra mắt của Tecno Spark 40C hứa hẹn mang đến một lựa chọn hấp dẫn trong phân khúc giá rẻ. Với thiết kế hiện đại cùng những trang bị như màn hình tần số quét 120Hz, viên pin dung lượng lớn 5000 mAh và cấu hình mạnh mẽ, chiếc điện thoại này đáp ứ...' WHERE [ProductName] = N'Tecno Spark 40C 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Sự ra mắt của vivo Y03 thực sự là một điểm sáng trong dòng sản phẩm giá rẻ của vivo. Với thiết kế tinh tế, màn hình sắc nét và hiệu năng tốt trong tầm giá, chiếc điện thoại này hứa hẹn sẽ mang đến cho bạn trải nghiệm sử dụng hàng ngày thật mượt m...' WHERE [ProductName] = N'vivo Y03 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO A5i là một lựa chọn đáng chú ý trong phân khúc điện thoại phổ thông. Với thiết kế mỏng nhẹ, độ bền đạt chuẩn quân đội Mỹ, viên pin khủng 5100 mAh, màn hình lớn sắc nét và cụm camera đáp ứng tốt nhu cầu cơ bản, thiết bị này sẵn sàng đồng hành...' WHERE [ProductName] = N'OPPO A5i 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'Sự xuất hiện của vivo Y04 chắc chắn sẽ mang đến cho người dùng thêm một lựa chọn hấp dẫn trong phân khúc điện thoại giá rẻ. Với thiết kế hiện đại, màn hình sắc nét và hiệu năng ổn định, sản phẩm này được kỳ vọng sẽ đáp ứng tốt nhu cầu sử dụng thườn...' WHERE [ProductName] = N'vivo Y04 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Tiếp nối sự thành công của dòng sản phẩm giá rẻ, Samsung Galaxy A06 5G hứa hẹn mang đến một trải nghiệm vượt trội với nhiều tính năng ấn tượng. Từ kết nối 5G tốc độ cao, màn hình 120Hz mượt mà đến camera độ phân giải cao và viên pin bền bỉ, chiếc...' WHERE [ProductName] = N'Samsung Galaxy A06 5G 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'realme Note 60 sở hữu ngoại hình thanh lịch, thời trang, kết hợp cùng hiệu năng vượt trội và hệ thống camera ấn tượng trong phân khúc. Đây hứa hẹn sẽ là một đối thủ nặng ký, không thể bỏ qua đối với những người dùng đang tìm kiếm một chiếc điện t...' WHERE [ProductName] = N'realme Note 60 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Xiaomi Redmi 13x hứa hẹn mang đến cho người dùng một trải nghiệm mượt mà, ấn tượng, là sự lựa chọn lý tưởng cho các công việc cũng như giải trí cơ bản với một mức giá dễ dàng tiếp cận.Ngoại hình sang trọng, thiết kế mỏng nhẹDù nằm trong phân khúc...' WHERE [ProductName] = N'Xiaomi Redmi 13x 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Motorola giới thiệu Moto G35 5G, sự kết hợp lý tưởng giữa phong cách và công nghệ trong tầm giá phải chăng. Thiết kế thanh lịch, màn hình sống động cùng với những tính năng chụp ảnh đa dạng của máy mang đến trải nghiệm tuyệt vời cho mọi nhu cầu h...' WHERE [ProductName] = N'Motorola G35 5G 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Đánh dấu sự góp mặt tiếp theo trong phân khúc smartphone giá rẻ của HONOR, HONOR X6c không chỉ là một thiết bị ấn tượng bởi thiết kế thanh lịch mà còn mang trong mình khả năng hoạt động mượt mà nhờ bộ vi xử lý ổn định, viên pin 5200 mAh mạnh mẽ, ...' WHERE [ProductName] = N'HONOR X6c 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO A5x hứa hẹn sẽ khuấy động thị trường điện thoại phổ thông với hàng loạt tính năng nổi bật. Được trang bị thiết kế siêu bền, pin dung lượng lớn cùng trải nghiệm hình ảnh và âm thanh sống động, thiết bị này không chỉ đáp ứng mọi nhu cầu cơ bản...' WHERE [ProductName] = N'OPPO A5x 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 02/2025, Xiaomi chính thức ra mắt dòng điện thoại giá rẻ mới mang tên Xiaomi Redmi 15C. Thiết bị không chỉ có màn hình kích thước lớn 6.88 inch mà còn sở hữu dung lượng pin ấn tượng lên đến 5160 mAh. Hơn thế nữa, sức mạnh từ con chip Helio ...' WHERE [ProductName] = N'Xiaomi Redmi 15C 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Hãng realme vừa trình làng chiếc realme C71, một đại diện đầy hứa hẹn trong phân khúc điện thoại giá rẻ. Máy nổi bật với khả năng kháng nước, kháng bụi vượt trội, camera 50 MP sắc nét đi kèm những tiện ích AI ấn tượng, và viên pin trâu đáp ứng tố...' WHERE [ProductName] = N'realme C71 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, OPPO đã chính thức cho ra mắt mẫu điện thoại OPPO A3x, một tân binh thuộc dòng OPPO A mang theo nhiều cải tiến đáng giá. Với điểm nhấn là màn hình sắc nét có độ sáng cao, hiệu năng hoạt động mượt mà, thời lượng pin vượt trội cùng thiết k...' WHERE [ProductName] = N'OPPO A3x 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Vừa qua, OPPO đã bổ sung một thành viên mới vào dòng A-series của mình mang tên OPPO A6x. Với ngoại hình bắt mắt, màn hình sáng rõ cùng viên pin dung lượng lớn, chiếc máy này hứa hẹn sẽ mang đến trải nghiệm sử dụng trọn vẹn suốt ngày dài cho ngườ...' WHERE [ProductName] = N'OPPO A6x 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'Bên cạnh các dòng smartphone thuộc phân khúc cao cấp, OPPO cũng rất chú trọng phát triển sản phẩm ở phân khúc tầm trung giá rẻ, điển hình là OPPO A6t vừa được ra mắt. Điện thoại hứa hẹn mang đến trải nghiệm sử dụng tuyệt vời với thiết kế mỏng nhẹ...' WHERE [ProductName] = N'OPPO A6t 4GB/64GB';
UPDATE [dbo].[Products] SET [Description] = N'realme C75x mang đến một diện mạo thanh lịch nhưng vô cùng cứng cáp, phù hợp cho những ai tìm kiếm sự cân bằng giữa thời trang và độ bền. Với viên pin khủng, màn hình bảo vệ mắt cùng hàng loạt tính năng hỗ trợ, thiết bị này sẵn sàng đồng hành cùn...' WHERE [ProductName] = N'realme C75x 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung tiếp tục khẳng định vị thế của mình trong phân khúc phổ thông bằng việc ra mắt Galaxy A17 LTE. Mẫu điện thoại mới nhất dòng Galaxy A này sở hữu màn hình rộng rãi, hệ thống camera chất lượng cùng hiệu suất ổn định và viên pin dung lượng lớ...' WHERE [ProductName] = N'Samsung Galaxy A17 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Đầu năm 2025, Xiaomi đã giới thiệu chiếc Redmi 15, một ứng viên sáng giá trong dòng smartphone phổ thông. Không chỉ sở hữu ngoại hình thu hút, thiết bị còn gây ấn tượng bởi hệ thống camera chất lượng 50 MP, màn hình tần số quét 120Hz mượt mà cù...' WHERE [ProductName] = N'Xiaomi Redmi 15 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'HONOR tiếp tục mang đến một sản phẩm chất lượng trong tầm giá với mẫu HONOR X7c. Chiếc điện thoại này sở hữu nhiều ưu điểm ấn tượng, từ thời lượng pin cực khủng, màn hình hiển thị lớn và sắc nét, đến cụm camera chụp ảnh tốt. Nếu bạn đang tìm kiếm...' WHERE [ProductName] = N'HONOR X7c 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung Galaxy A16 sở hữu thiết kế thời thượng, hiệu năng ổn định, pin cực trâu và màn hình lớn, mang lại trải nghiệm sử dụng tuyệt vời. Với hàng loạt cải tiến và tính năng nổi bật, Galaxy A16 chắc chắn sẽ là một trong những sản phẩm đáng chú ý t...' WHERE [ProductName] = N'Samsung Galaxy A16 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO A3 nổi bật trong phân khúc giá nhờ sự kết hợp hoàn hảo giữa độ bền bỉ đáng kinh ngạc, viên pin dung lượng cao và công nghệ sạc cực nhanh. Đi kèm là hệ thống camera chất lượng, đáp ứng tốt nhu cầu nhiếp ảnh, cùng một thiết kế hiện đại, trẻ tr...' WHERE [ProductName] = N'OPPO A3 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại Xiaomi Redmi Note 14 thu hút ánh nhìn nhờ thiết kế thời thượng, màn hình rực rỡ và mượt mà, camera ấn tượng cùng pin lớn và sạc nhanh vượt trội. Máy đáp ứng tốt mọi nhu cầu từ giải trí, chơi game cho đến sử dụng hàng ngày, hứa hẹn tr...' WHERE [ProductName] = N'Xiaomi Redmi Note 14 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây Tecno đã cho ra mắt Tecno POVA 7, một lựa chọn đáng cân nhắc với thiết kế cá tính, màn hình rộng rãi cùng viên pin dung lượng "khủng". Đây hứa hẹn sẽ là chiếc điện thoại giá rẻ mang lại trải nghiệm giải trí liên tục suốt ngày dài, đáp...' WHERE [ProductName] = N'Tecno Pova 7 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'vivo tiếp tục chứng minh khả năng cung cấp các sản phẩm chất lượng trong phân khúc giá rẻ với chiếc điện thoại vivo Y19s Pro mới ra mắt. Máy sở hữu thiết kế vô cùng sang trọng, được kết hợp với pin dung lượng lớn, màn hình mượt mà, đáp ứng tốt nh...' WHERE [ProductName] = N'vivo Y19s Pro 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Honor đã cho ra mắt HONOR X8c, một lựa chọn hấp dẫn trong phân khúc phổ thông. Sản phẩm này gây ấn tượng mạnh với dung lượng pin siêu lớn, thiết kế bền bỉ với độ hoàn thiện cao, màn hình hiển thị sắc nét và hệ thống camera ấn tượng. Dưới đây là n...' WHERE [ProductName] = N'HONOR X8c 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, realme đã làm nóng thị trường smartphone với chiếc realme C75, một sản phẩm sở hữu hàng loạt công nghệ tiên tiến như kháng nước bụi cao cấp, độ bền vượt trội, dung lượng pin khủng cùng sạc nhanh siêu tốc. Cùng khám phá những điểm nổi bật...' WHERE [ProductName] = N'realme C75 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Xiaomi đã ra mắt phiên bản Xiaomi Redmi 15 5G với khả năng kết nối mạng hiện đại, màn hình có tần số quét lớn cùng thiết kế đẹp mắt. Với những công nghệ thông minh mà điện thoại cung cấp, chắc chắn bạn sẽ có trải nghiệm sử dụng khó quên.Thiết kế ...' WHERE [ProductName] = N'Xiaomi Redmi 15 5G 4GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Tiếp nối sự thành công của X7c, đầu năm 2025, HONOR đã mang đến thị trường mẫu HONOR X7d. Smartphone này không chỉ kế thừa thiết kế đẹp mắt và viên pin siêu bền, mà còn được nâng cấp khả năng xử lý mạnh mẽ cùng màn hình mượt mà, mang lại trải ngh...' WHERE [ProductName] = N'Honor X7d 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 12/2024, Xiaomi tiếp tục củng cố vị thế vững chắc trong phân khúc tầm trung bằng việc trình làng Redmi Note 14 Pro. Không chỉ sở hữu diện mạo hiện đại với khả năng kháng nước ấn tượng, mẫu điện thoại này còn ghi điểm nhờ hiệu năng mượt mà t...' WHERE [ProductName] = N'Xiaomi Redmi Note 14 Pro 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào tháng 04/2024, OPPO chính thức ra mắt OPPO A60, một đại diện mới cho phân khúc điện thoại tầm trung với mức giá dễ tiếp cận. Thiết bị gây ấn tượng bởi thiết kế hiện đại, mỏng nhẹ, pin lớn cùng khả năng chống nước, sạc nhanh và độ sáng màn hìn...' WHERE [ProductName] = N'OPPO A60 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung Galaxy A16 5G 8GB/256GB là phiên bản nổi bật trong phân khúc tầm trung của Samsung, không chỉ gây ấn tượng bởi bộ nhớ lưu trữ lớn mà còn đi kèm với loạt công nghệ hiện đại. Cùng khám phá chi tiết các tính năng hấp dẫn của chiếc smartphone...' WHERE [ProductName] = N'Samsung Galaxy A16 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại vivo Y29 là minh chứng hoàn hảo cho sự kết hợp giữa thiết kế độc đáo và các tính năng mạnh mẽ. Sản phẩm không chỉ gây ấn tượng nhờ vẻ ngoài bắt mắt mà còn tích hợp nhiều tiện ích như sạc nhanh vượt trội, dung lượng pin bền bỉ và hệ thố...' WHERE [ProductName] = N'vivo Y29 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Đầu năm 2025, Samsung đã trình làng một dòng điện thoại mới, trong đó mẫu Samsung Galaxy A17 5G thuộc phân khúc tầm trung thu hút nhiều sự chú ý. Sở hữu thiết kế hiện đại, kết nối mạng 5G nhanh chóng cùng nhiều thông số kỹ thuật ấn tượng, sản phẩ...' WHERE [ProductName] = N'Samsung Galaxy A17 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 05/2024, điện thoại HONOR X8b gây chú ý với sự xuất hiện của hàng loạt công nghệ đáng giá, từ màn hình AMOLED, camera độ phân giải cao cho đến dung lượng RAM cực lớn so với mức giá hãng đề ra, đem đến một lựa chọn cực kỳ lý tưởng cho những ...' WHERE [ProductName] = N'HONOR X8b 8GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung Galaxy A26 5G là mẫu điện thoại tầm trung mới từ Samsung, mang đến cho người dùng một sự kết hợp hoàn hảo giữa thiết kế hiện đại, màn hình sắc nét và cấu hình mạnh mẽ. Với mức giá dễ tiếp cận, chiếc smartphone này hứa hẹn sẽ trở thành lựa...' WHERE [ProductName] = N'Samsung Galaxy A26 5G 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO A5 Pro ra mắt với thiết kế cứng cáp cùng viên pin dung lượng lớn và khả năng chụp ảnh sắc nét đáng kinh ngạc. Điểm nhấn của máy là sức mạnh đến từ con chip tiên tiến cùng công nghệ sạc cực nhanh. Điện thoại mang thiết kế siêu mỏng và nổi bật...' WHERE [ProductName] = N'OPPO A5 Pro 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại HONOR X9c Smart 5G mang đến một lựa chọn đáng giá trong phân khúc tầm trung với độ bền siêu ấn tượng, màn hình hiển thị xuất sắc, viên pin siêu lớn và cấu hình đủ tốt cho mọi nhu cầu hằng ngày.Độ bền vượt trội – Chống rơi, chống nước v...' WHERE [ProductName] = N'HONOR X9c Smart 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'vivo đã chính thức giới thiệu mẫu điện thoại vivo Y21d, một đại diện mới trong phân khúc tầm trung sở hữu nhiều điểm nổi bật đáng chú ý. Thiết kế mỏng nhẹ, bắt mắt, cùng thời lượng pin bền bỉ và khả năng sạc siêu tốc hứa hẹn sẽ mang đến cho người...' WHERE [ProductName] = N'vivo Y21d 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Gần đây, OPPO đã trình làng dòng sản phẩm giá rẻ ấn tượng mang tên OPPO A5, không chỉ nổi bật với thiết kế siêu bền mà còn sở hữu pin 5100 mAh cho khả năng hoạt động suốt ngày dài. Màn hình rực rỡ và hiệu suất ổn định mang đến cho bạn trải nghiệm...' WHERE [ProductName] = N'OPPO A5 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'vivo Y28 mang đến nhiều điểm nổi bật trong phân khúc tầm trung. Với thiết kế đẹp mắt, hiệu năng vượt trội và hệ thống camera tiên tiến, chiếc điện thoại này hứa hẹn sẽ thu hút sự quan tâm của nhiều người tiêu dùng, từ học sinh sinh viên đến nhân ...' WHERE [ProductName] = N'vivo Y28 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, HONOR đã chính thức ra mắt mẫu smartphone mới mang tên HONOR X7d 5G. Nhờ trang bị kết nối 5G tiên tiến, bộ vi xử lý mạnh mẽ, màn hình mượt mà cùng dung lượng pin siêu khủng 6000 mAh, chiếc điện thoại này hứa hẹn đáp ứng tốt nhu cầu sử dụ...' WHERE [ProductName] = N'Honor X7d 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại Xiaomi Redmi Note 14 5G với khả năng kết nối tiên tiến hứa hẹn sẽ làm hài lòng người dùng. Máy được ưu ái trang bị nhiều thông số nổi bật như màn hình hiển thị sống động, hệ thống camera xuất sắc, cùng thời lượng pin cực khủng và sạc s...' WHERE [ProductName] = N'Xiaomi Redmi Note 14 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Motorola Moto G57 Power 5G xuất hiện như một "hiện tượng" trong phân khúc tầm trung, thu hút sự chú ý với loạt điểm sáng như dung lượng pin "khủng", màn hình lớn sắc nét, và đặc biệt là hệ thống camera 50 MP tiên tiến. Đây thực sự là lựa chọn đán...' WHERE [ProductName] = N'Motorola G57 Power 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, Motorola đã ra mắt Moto G86 5G, một mẫu smartphone trong phân khúc tầm trung không chỉ mang diện mạo đẳng cấp mà còn sở hữu nhiều điểm nổi bật như màn hình pOLED sắc nét, thiết kế cực mỏng và hệ thống camera ấn tượng mang đến những trải ...' WHERE [ProductName] = N'Motorola G86 POWER 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'vivo lại một lần nữa mang đến cho người dùng một chiếc smartphone tầm trung đầy ấn tượng mang tên vivo V40 Lite. Sở hữu một thiết kế ngoại hình đẹp mắt, kết hợp với hệ thống đèn Aura Light thế hệ mới và tính năng sạc nhanh vượt trội, đây không ch...' WHERE [ProductName] = N'vivo V40 Lite 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO lại tiếp tục khuấy động thị trường với sự xuất hiện của dòng Reno13. Trong đó, mẫu OPPO Reno13 F nổi bật với diện mạo vô cùng độc đáo, kết hợp cụm camera được nâng cấp vượt bậc so với phiên bản tiền nhiệm và những tính năng AI tiên tiến, hứa...' WHERE [ProductName] = N'OPPO Reno13 F 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'HONOR 400 Lite sở hữu thiết kế thời trang, cấu hình mạnh mẽ, camera độ phân giải cao và màn hình ấn tượng, hứa hẹn mang đến cho người dùng những trải nghiệm tuyệt vời.Với mức giá hợp lý, chiếc điện thoại này phù hợp với nhiều đối tượng người dùng...' WHERE [ProductName] = N'HONOR 400 Lite 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 05/2024, OPPO tung ra thị trường chiếc OPPO A60 với thiết kế hiện đại, mỏng nhẹ, pin lớn cùng khả năng chống nước, sạc nhanh và độ sáng màn hình ấn tượng, hứa hẹn mang đến cho người dùng những trải nghiệm tuyệt vời.Thiết kế hiện đại, trẻ tr...' WHERE [ProductName] = N'OPPO A60 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung Galaxy A16 5G nổi bật trong phân khúc tầm trung nhờ trang bị bộ nhớ lưu trữ lớn, viên pin siêu khỏe cùng nhiều công nghệ tiên tiến khác, hứa hẹn mang đến trải nghiệm tuyệt vời cho người dùng.Thiết kế hiện đại, trẻ trungSản phẩm vẫn mang p...' WHERE [ProductName] = N'Samsung Galaxy A16 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại vivo Y29 là minh chứng hoàn hảo cho sự kết hợp giữa thiết kế độc đáo và các tính năng mạnh mẽ. Sản phẩm không chỉ gây ấn tượng nhờ vẻ ngoài bắt mắt mà còn tích hợp nhiều tiện ích như sạc nhanh vượt trội, dung lượng pin bền bỉ và hệ thố...' WHERE [ProductName] = N'vivo Y29 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Đầu năm 2025, Samsung đã trình làng một dòng điện thoại mới, trong đó mẫu Samsung Galaxy A17 5G thuộc phân khúc tầm trung thu hút nhiều sự chú ý. Sở hữu thiết kế hiện đại, kết nối mạng 5G nhanh chóng cùng nhiều thông số kỹ thuật ấn tượng, sản phẩ...' WHERE [ProductName] = N'Samsung Galaxy A17 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 05/2024, điện thoại HONOR X8b gây chú ý với sự xuất hiện của hàng loạt công nghệ đáng giá, từ màn hình AMOLED, camera độ phân giải cao cho đến dung lượng RAM cực lớn so với mức giá hãng đề ra, đem đến một lựa chọn cực kỳ lý tưởng cho những ...' WHERE [ProductName] = N'HONOR X8b 8GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung Galaxy A26 5G là mẫu điện thoại tầm trung mới từ Samsung, mang đến cho người dùng một sự kết hợp hoàn hảo giữa thiết kế hiện đại, màn hình sắc nét và cấu hình mạnh mẽ. Với mức giá dễ tiếp cận, chiếc smartphone này hứa hẹn sẽ trở thành lựa...' WHERE [ProductName] = N'Samsung Galaxy A26 5G 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 02/2025, realme đã chính thức bổ sung chiếc realme C85 vào bộ sưu tập C-Series của hãng. Mẫu điện thoại này ghi dấu ấn với khả năng kháng nước chuẩn IP64 cao cấp, màn hình rực rỡ với tần số quét 120Hz mượt mà và camera chất lượng 50 MP, hứa...' WHERE [ProductName] = N'realme C85 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO A5 Pro ra mắt với thiết kế cứng cáp cùng viên pin dung lượng lớn và khả năng chụp ảnh sắc nét đáng kinh ngạc. Điểm nhấn của máy là sức mạnh đến từ con chip tiên tiến cùng công nghệ sạc cực nhanh. Điện thoại mang thiết kế siêu mỏng và nổi bật...' WHERE [ProductName] = N'OPPO A5 Pro 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại HONOR X9c Smart 5G mang đến một lựa chọn đáng giá trong phân khúc tầm trung với độ bền siêu ấn tượng, màn hình hiển thị xuất sắc, viên pin siêu lớn và cấu hình đủ tốt cho mọi nhu cầu hằng ngày.Độ bền vượt trội – Chống rơi, chống nước v...' WHERE [ProductName] = N'HONOR X9c Smart 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'vivo đã chính thức giới thiệu mẫu điện thoại vivo Y21d, một đại diện mới trong phân khúc tầm trung sở hữu nhiều điểm nổi bật đáng chú ý. Thiết kế mỏng nhẹ, bắt mắt, cùng thời lượng pin bền bỉ và khả năng sạc siêu tốc hứa hẹn sẽ mang đến cho người...' WHERE [ProductName] = N'vivo Y21d 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Gần đây, OPPO đã trình làng dòng sản phẩm giá rẻ ấn tượng mang tên OPPO A5, không chỉ nổi bật với thiết kế siêu bền mà còn sở hữu pin 5100 mAh cho khả năng hoạt động suốt ngày dài. Màn hình rực rỡ và hiệu suất ổn định mang đến cho bạn trải nghiệm...' WHERE [ProductName] = N'OPPO A5 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO A5i Pro là một chiếc điện thoại giá rẻ đáng chú ý, nổi bật với thiết kế siêu bền, dung lượng pin cực khủng, màn hình kích thước lớn và hiệu năng mượt mà. Đây là một sự lựa chọn tuyệt vời cho những ai đang tìm kiếm một chiếc điện thoại bền bỉ...' WHERE [ProductName] = N'OPPO A5i Pro 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'vivo Y28 mang đến nhiều điểm nổi bật trong phân khúc tầm trung. Với thiết kế đẹp mắt, hiệu năng vượt trội và hệ thống camera tiên tiến, chiếc điện thoại này hứa hẹn sẽ thu hút sự quan tâm của nhiều người tiêu dùng, từ học sinh sinh viên đến nhân ...' WHERE [ProductName] = N'vivo Y28 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, HONOR đã chính thức ra mắt mẫu smartphone mới mang tên HONOR X7d 5G. Nhờ trang bị kết nối 5G tiên tiến, bộ vi xử lý mạnh mẽ, màn hình mượt mà cùng dung lượng pin siêu khủng 6000 mAh, chiếc điện thoại này hứa hẹn đáp ứng tốt nhu cầu sử dụ...' WHERE [ProductName] = N'Honor X7d 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại Xiaomi Redmi Note 14 5G với khả năng kết nối tiên tiến hứa hẹn sẽ làm hài lòng người dùng. Máy được ưu ái trang bị nhiều thông số nổi bật như màn hình hiển thị sống động, hệ thống camera xuất sắc, cùng thời lượng pin cực khủng và sạc s...' WHERE [ProductName] = N'Xiaomi Redmi Note 14 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Năm 2025, realme đã ra mắt mẫu smartphone mới mang tên realme C85 Pro, mang đến sự kết hợp hoàn hảo giữa diện mạo đầy phong cách và những cải tiến công nghệ đáng chú ý, với hệ thống camera chất lượng cùng hiệu suất hoạt động mượt mà và ổn định. S...' WHERE [ProductName] = N'realme C85 Pro 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Motorola Moto G57 Power 5G xuất hiện như một "hiện tượng" trong phân khúc tầm trung, thu hút sự chú ý với loạt điểm sáng như dung lượng pin "khủng", màn hình lớn sắc nét, và đặc biệt là hệ thống camera 50 MP tiên tiến. Đây thực sự là lựa chọn đán...' WHERE [ProductName] = N'Motorola G57 Power 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, Motorola đã ra mắt Moto G86 5G, một mẫu smartphone trong phân khúc tầm trung không chỉ mang diện mạo đẳng cấp mà còn sở hữu nhiều điểm nổi bật như màn hình pOLED sắc nét, thiết kế cực mỏng và hệ thống camera ấn tượng mang đến những trải ...' WHERE [ProductName] = N'Motorola G86 POWER 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'vivo lại một lần nữa mang đến cho người dùng một chiếc smartphone tầm trung đầy ấn tượng mang tên vivo V40 Lite. Sở hữu một thiết kế ngoại hình đẹp mắt, kết hợp với hệ thống đèn Aura Light thế hệ mới và tính năng sạc nhanh vượt trội, đây không ch...' WHERE [ProductName] = N'vivo V40 Lite 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại Xiaomi Redmi Note 15 5G với thiết kế thời thượng, màn hình mượt mà sắc nét, camera chụp ảnh đỉnh cao và dung lượng pin khủng, sạc siêu tốc. Phù hợp cho giải trí, chơi game và sử dụng hàng ngày.Thiết kế hiện đại, mỏng nhẹ thời trangSở h...' WHERE [ProductName] = N'Xiaomi Redmi Note 15 5G 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'vivo Y39 5G là mẫu smartphone tầm trung đầy hứa hẹn, kết hợp hoàn hảo giữa thiết kế thanh lịch, hiệu suất bền bỉ và các tính năng hiện đại. Máy được trang bị cấu hình ổn định, màn hình hiển thị xuất sắc, kết nối 5G thần tốc và hệ thống camera sắ...' WHERE [ProductName] = N'vivo Y39 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Sự xuất hiện của Xiaomi Redmi Note 14 Pro 5G được xem như một lựa chọn sáng giá trong phân khúc tầm trung. Với thiết kế tinh tế, màn hình sắc nét và hiệu năng mạnh mẽ, chiếc điện thoại này hứa hẹn sẽ mang đến cho người dùng trải nghiệm mượt mà và...' WHERE [ProductName] = N'Xiaomi Redmi Note 14 Pro 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO lại tiếp tục khuấy động thị trường với sự xuất hiện của dòng Reno13. Trong đó, mẫu OPPO Reno13 F nổi bật với diện mạo vô cùng độc đáo, kết hợp cụm camera được nâng cấp vượt bậc so với phiên bản tiền nhiệm và những tính năng AI tiên tiến, hứa...' WHERE [ProductName] = N'OPPO Reno13 F 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'realme đã cho ra mắt chiếc realme C85 5G thuộc phân khúc tầm trung, gây ấn tượng mạnh nhờ màn hình rực rỡ, dung lượng pin bền bỉ, hỗ trợ kết nối 5G tốc độ cao và đặc biệt là chuẩn kháng nước bụi IP64, hứa hẹn đáp ứng tốt mọi nhu cầu hàng ngày của...' WHERE [ProductName] = N'realme C85 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'HONOR 400 Lite sở hữu thiết kế thời trang, cấu hình mạnh mẽ, camera độ phân giải cao và màn hình ấn tượng, hứa hẹn mang đến cho người dùng những trải nghiệm tuyệt vời.Với mức giá hợp lý, chiếc điện thoại này phù hợp với nhiều đối tượng người dùng...' WHERE [ProductName] = N'HONOR 400 Lite 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào giữa tháng 12/2024, hãng vivo đã chính thức trình làng mẫu smartphone mới thuộc phân khúc tầm trung mang tên vivo V50 Lite 8GB/256GB. Thiết bị này nhanh chóng thu hút sự quan tâm nhờ thiết kế tinh tế, hiệu năng mạnh mẽ, thời lượng pin bền bỉ ...' WHERE [ProductName] = N'vivo V50 Lite 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Gia nhập thị trường vào tháng 2/2025, HONOR X8d nhanh chóng thu hút sự chú ý nhờ thiết kế hiện đại, màn hình sắc nét và hệ thống camera ấn tượng, cùng với dung lượng pin bền bỉ, sẵn sàng đồng hành cùng bạn suốt cả ngày dài.Màn hình cong ấn tượng...' WHERE [ProductName] = N'HONOR X8d 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Với sự ra mắt của vivo Y31d, vivo mang đến một thiết bị nổi bật với hàng loạt tính năng ấn tượng trong phân khúc. Từ thiết kế tinh tế, thanh lịch đến dung lượng pin lớn, sản phẩm này còn được trang bị vi xử lý ổn định để đáp ứng mượt mà nhiều nhu...' WHERE [ProductName] = N'vivo Y31d 6GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, OPPO đã chính thức trình làng phiên bản OPPO A6 thuộc dòng A-Series mới của hãng. Với màn hình OLED sắc nét, dung lượng pin lớn cùng công nghệ sạc nhanh, sản phẩm này hứa hẹn sẽ mang đến trải nghiệm tuyệt vời và đáng giá cho người dùng.T...' WHERE [ProductName] = N'OPPO A6 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Với thiết kế sang trọng, hiệu suất mạnh mẽ và màn hình sắc nét, OPPO A6 Pro là chiếc smartphone hoàn hảo cho mọi nhu cầu từ làm việc, giải trí đến chụp ảnh sắc nét, hứa hẹn mang đến trải nghiệm sử dụng trọn vẹn.Thiết kế bắt mắt đầy ấn tượngOPPO ...' WHERE [ProductName] = N'OPPO A6 Pro 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại vivo V50 Lite 5G chính thức ra mắt, hứa hẹn mang đến trải nghiệm tuyệt vời với màn hình AMOLED rực rỡ, kết nối 5G tốc độ cao, hiệu năng mượt mà và khả năng sạc nhanh ấn tượng, phục vụ hoàn hảo cho mọi nhu cầu hằng ngày của người dùng.T...' WHERE [ProductName] = N'vivo V50 Lite 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, realme đã bổ sung vào phân khúc tầm trung mẫu điện thoại realme 15T 5G. Thiết bị sở hữu những thông số cực kì ấn tượng như màn hình đục lỗ siêu sáng, sạc nhanh 45W, pin "khủng" đi kèm hệ thống camera AI 50 MP, đáp ứng đa dạng nhu cầu của...' WHERE [ProductName] = N'realme 15T 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Xiaomi Redmi Note 15 Pro sở hữu thiết kế hiện đại, camera vượt trội và viên pin khủng cùng công nghệ sạc cực nhanh mang lại trải nghiệm tối ưu. Máy đáp ứng tốt mọi nhu cầu từ giải trí, nhiếp ảnh đến hiệu năng mạnh mẽ suốt cả ngày dài.Thiết kế h...' WHERE [ProductName] = N'Xiaomi Redmi Note 15 Pro 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 02/2025, Motorola đã ra mắt Moto Edge 60 Fusion, chiếc điện thoại sở hữu nhiều điểm nổi bật trong phân khúc tầm trung. Với thiết kế tinh tế, camera vượt trội và hiệu năng mạnh mẽ, máy hứa hẹn sẽ đáp ứng đa dạng nhu cầu của người dùng, từ g...' WHERE [ProductName] = N'Motorola Edge 60 Fusion 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 1/2025, hãng realme chính thức giới thiệu chiếc điện thoại tầm trung mới mang tên realme 14 5G. Thiết bị nhanh chóng ghi điểm với thiết kế siêu mỏng tinh tế, hiệu năng mạnh mẽ xử lý tốt các tác vụ nặng, hỗ trợ mạng 5G tốc độ cao và đặc biệt...' WHERE [ProductName] = N'realme 14 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, OPPO đã trình làng thêm phiên bản OPPO Reno14 F 5G (8GB/256GB), một dòng smartphone cận cao cấp, có mức giá siêu dễ tiếp cận. Thiết bị không chỉ thu hút bởi vẻ ngoài thời thượng mà còn mang đến trải nghiệm vượt trội với tính năng AI tiên...' WHERE [ProductName] = N'OPPO Reno14 F 5G 8GB/256GB Hồng';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại Xiaomi Redmi Note 14 Pro+ 5G nổi bật với hệ thống camera chất lượng cao, cung cấp những bức ảnh sắc nét và chi tiết. Bên cạnh đó, viên pin dung lượng lớn 6200 mAh cùng nhiều thông số ấn tượng khác hứa hẹn sẽ là một lựa chọn đáng cân nh...' WHERE [ProductName] = N'Xiaomi Redmi Note 14 Pro+ 5G 12GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, Samsung đã chính thức ra mắt mẫu điện thoại tầm trung Galaxy A36 5G, nhanh chóng thu hút sự chú ý của người dùng. Sản phẩm nổi bật với màn hình Super AMOLED sắc nét cùng thiết kế mỏng nhẹ tinh tế và loạt tiện ích từ Galaxy AI đi kèm, hứa...' WHERE [ProductName] = N'Samsung Galaxy A36 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Năm 2025, realme đã làm mới dòng sản phẩm tầm trung của mình với sự ra mắt của chiếc realme 15 5G. Được trang bị thiết kế tinh tế, hiệu năng ấn tượng, hỗ trợ mạng 5G thần tốc và hệ thống camera xuất sắc, thiết bị này chắc chắn sẽ đáp ứng tốt mọi ...' WHERE [ProductName] = N'realme 15 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Xiaomi Redmi Note 15 Pro 5G được trang bị cấu hình ấn tượng với nhiều cải tiến từ ngoại hình, camera lẫn khả năng sạc ấn tượng. Không chỉ mang đến sức mạnh kết nối 5G tốc độ cao mà còn tối ưu hóa trải nghiệm giải trí và làm việc của người dùng, x...' WHERE [ProductName] = N'Xiaomi Redmi Note 15 Pro 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 05/2024, hãng vivo đã tung ra một chiếc điện thoại tầm trung mang tên vivo V30e 5G nổi bật với hàng loạt công nghệ hiện đại. Từ hệ thống camera chất lượng, màn hình cong siêu nét, đến viên pin dung lượng lớn và thiết kế bắt mắt, sản phẩm nà...' WHERE [ProductName] = N'vivo V30e 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Đầu năm 2025, Samsung đã trình làng một dòng điện thoại tầm trung ấn tượng mới mang tên Samsung Galaxy A56 5G. Với thiết kế tinh tế kết hợp hiệu năng mượt mà và kết nối 5G mạnh mẽ, thiết bị này hứa hẹn sẽ mang đến cho người dùng những trải nghiệm...' WHERE [ProductName] = N'Samsung Galaxy A56 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Với việc ra mắt mẫu vivo V60 Lite 5G, hãng vivo tiếp tục khẳng định vị thế của mình trên thị trường smartphone. Không chỉ sở hữu thiết kế mỏng nhẹ, thanh lịch và khả năng sạc vượt trội, sản phẩm còn được trang bị đèn Aura Light, một điểm nhấn đặc...' WHERE [ProductName] = N'vivo V60 Lite 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào tháng 11/2024, nhà HONOR đã tung ra mẫu smartphone HONOR X9d 5G mang theo nhiều nâng cấp ấn tượng, đặc biệt là thiết kế mỏng nhẹ đáng kinh ngạc, viên pin bền bỉ và cấu hình mạnh mẽ, hứa hẹn sẽ "khuấy đảo" phân khúc tầm trung.Ngoại hình sang t...' WHERE [ProductName] = N'HONOR X9d 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO A6 Pro 5G mang đến hàng loạt cải tiến đột phá, từ thiết kế sang trọng, thanh lịch đến hiệu năng vượt trội. Nổi bật với các tính năng hiện đại như sạc siêu nhanh, camera độ phân giải cao và khả năng kết nối 5G ấn tượng, chiếc smartphone này h...' WHERE [ProductName] = N'OPPO A6 Pro 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào tháng 11/2024, OPPO đã trình làng dòng sản phẩm Reno14 series, với mẫu Reno14 F 5G (12GB/256GB) là một điểm sáng nổi bật. Chiếc smartphone này mang đến diện mạo độc đáo, khả năng nhiếp ảnh nâng cao và các tính năng AI hiện đại, hứa hẹn cung c...' WHERE [ProductName] = N'OPPO Reno14 F 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vivo V40 ra mắt và mang đến một luồng gió mới trong phân khúc giá của mình. Với sự kết hợp hoàn hảo giữa thiết kế mỏng nhẹ, hiệu năng mạnh mẽ và hệ thống camera ấn tượng, chiếc điện thoại này hứa hẹn sẽ đáp ứng trọn vẹn nhu cầu của những người dù...' WHERE [ProductName] = N'vivo V40 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'realme 16 5G vừa ra mắt đã nhanh chóng thu hút sự chú ý trên thị trường với thiết kế trẻ trung, cuốn hút và bộ tính năng được tối ưu hoàn hảo. Đây thực sự là một chiếc smartphone đáp ứng trọn vẹn nhu cầu của những người dùng năng động, khao khát ...' WHERE [ProductName] = N'realme 16 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào cuối tháng 02/2025, OPPO đã giới thiệu mẫu Reno15 F 5G tới tay người tiêu dùng Việt. Chiếc điện thoại này tạo ấn tượng với vẻ ngoài tinh tế, hiệu suất ổn định và một bộ camera đáp ứng tốt nhu cầu chụp ảnh hằng ngày. Hứa hẹn sẽ là người bạn đ...' WHERE [ProductName] = N'OPPO Reno15 F 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 02/2025, HONOR ra mắt dòng smartphone HONOR 400 5G, thiết bị nhanh chóng thu hút sự quan tâm của giới công nghệ. Điểm mạnh của chiếc điện thoại này nằm ở ngoại hình sang trọng với độ mỏng ấn tượng, khả năng nhiếp ảnh vượt trội cùng hiệu năn...' WHERE [ProductName] = N'HONOR 400 5G 12GB/256GB Đen';
UPDATE [dbo].[Products] SET [Description] = N'Sự ra mắt của dòng OPPO Reno13 5G đánh dấu một bước tiến mạnh mẽ trong thiết kế di động, với vẻ ngoài thanh lịch và những gam màu trẻ trung. Không chỉ dừng lại ở ngoại hình ấn tượng, thiết bị còn hứa hẹn nâng cao trải nghiệm chụp ảnh của bạn nhờ ...' WHERE [ProductName] = N'OPPO Reno13 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Motorola giới thiệu Moto Edge 70 thuộc phân khúc tầm trung. Với thiết kế mỏng nhẹ, màn hình xuất sắc và hệ thống camera chất lượng, chiếc điện thoại này chắc chắn sẽ là một ứng viên đáng gờm, mang lại những trải nghiệm sử dụng trọn vẹn cho người ...' WHERE [ProductName] = N'Motorola Edge 70 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại iPhone 13 128 GB nổi bật với thiết kế cứng cáp cùng cụm camera kép được xếp chéo, hiệu năng đột phá nhờ con chip A15 Bionic và thời lượng pin được cải thiện, hứa hẹn sẽ mang đến những trải nghiệm sử dụng tuyệt vời.Hiệu năng mạnh mẽ với...' WHERE [ProductName] = N'iPhone 13 128GB';
UPDATE [dbo].[Products] SET [Description] = N'Xiaomi vừa giới thiệu một mẫu điện thoại cao cấp mang tên Xiaomi Redmi Note 15 Pro+ 5G. Thiết bị nổi bật nhờ dung lượng pin cực khỏe cùng công nghệ sạc cực nhanh ấn tượng. Màn hình sắc nét và mượt mà, kết hợp hiệu suất vượt trội, giúp máy có khả ...' WHERE [ProductName] = N'Xiaomi Redmi Note 15 Pro+ 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, Samsung đã trình làng một dòng điện thoại cận cao cấp mới mang tên Samsung Galaxy S24 FE 5G, hứa hẹn đem đến những trải nghiệm mượt mà cùng với đó là nhiều tính năng Galaxy AI thông minh, hỗ trợ đa dạng nhu cầu người dùng hiện nay.Điểm n...' WHERE [ProductName] = N'Samsung Galaxy S24 FE 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Sự xuất hiện của realme 15 Pro 5G được kỳ vọng sẽ đem đến một lựa chọn hấp dẫn trong phân khúc tầm trung và cận cao cấp. Chiếc điện thoại này sở hữu vẻ ngoài thanh lịch, màn hình sống động, camera chất lượng cùng hiệu năng mạnh mẽ, hứa hẹn đem lạ...' WHERE [ProductName] = N'realme 15 Pro 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào đầu năm 2025, dòng sản phẩm Galaxy S25 Fan Edition (FE) của Samsung chính thức lộ diện. Trong đó, mẫu điện thoại Galaxy S25 FE hứa hẹn mang đến trải nghiệm tuyệt vời với thiết kế mỏng nhẹ hiện đại, các tính năng Galaxy AI thông minh cùng hệ t...' WHERE [ProductName] = N'Samsung Galaxy S25 FE 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Xiaomi 15T 5G (12GB/512GB) là chiếc điện thoại mới thuộc dòng T-series của Xiaomi, thu hút sự chú ý với vẻ ngoài tinh tế cùng loạt tính năng vượt trội. Nổi bật với hiệu năng đỉnh cao, sạc cực nhanh và hệ thống camera mang đậm dấu ấn Leica, đây th...' WHERE [ProductName] = N'Xiaomi 15T 5G 12GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Xiaomi 15T 5G là mẫu điện thoại cận cao cấp mang đậm triết lý thiết kế thanh lịch nhưng không kém phần sang trọng. Điểm sáng của sản phẩm nằm ở sự hỗ trợ từ camera Leica, mang đến chất lượng nhiếp ảnh chuẩn studio, cùng hiệu năng đỉnh cao và tốc ...' WHERE [ProductName] = N'Xiaomi 15T 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Trong tháng 10 năm 2023, OPPO đã giới thiệu mẫu điện thoại gập đầu tiên của hãng tại thị trường Việt Nam với tên gọi OPPO Find N3 Flip 5G. Chiếc điện thoại này không chỉ mang đến diện mạo đầy độc đáo mà còn ấn tượng với bản lề bền bỉ cùng màn hìn...' WHERE [ProductName] = N'OPPO Find N3 Flip 5G 12GB/256GB Hồng';
UPDATE [dbo].[Products] SET [Description] = N'Sau sự xuất hiện của dòng iPhone 13 thì đến đầu tháng 09/2022 mẫu điện thoại iPhone 14 128GB cũng đã chính thức được lộ diện. Chiếc điện thoại này mang trong mình vẻ ngoài đẹp mắt với mặt lưng phẳng cùng đa dạng màu sắc trẻ trung. Khả năng quay c...' WHERE [ProductName] = N'iPhone 14 128GB';
UPDATE [dbo].[Products] SET [Description] = N'Sự xuất hiện của chiếc điện thoại realme 16 Pro 5G đánh dấu một bước tiến mới đầy hứa hẹn, khi kết hợp hoàn hảo giữa phong cách hiện đại và sức mạnh đỉnh cao. Nổi bật với cấu hình mạnh mẽ, hiệu suất chụp ảnh ưu việt và công nghệ màn hình tiên tiế...' WHERE [ProductName] = N'realme 16 Pro 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào tháng 01/2024 dòng điện thoại flagship mới của hãng Samsung chính thức được trình làng. Trong đó, mẫu điện thoại Samsung Galaxy S24 256GB thu hút sự chú ý khi mang đến thiết kế nhỏ gọn, tích hợp con chip mới cực kỳ mạnh mẽ đi cùng đa dạng các...' WHERE [ProductName] = N'Samsung Galaxy S24 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Trong năm 2024, hãng vivo đã chính thức giới thiệu chiếc vivo V60 thuộc dòng V-Series mới. Máy nhanh chóng thu hút người dùng với thiết kế thanh lịch, màn hình sống động, sạc nhanh ấn tượng cùng khả năng quay phim nhiếp ảnh chất lượng cao. Diện m...' WHERE [ProductName] = N'vivo V60 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO đã đánh dấu sự trở lại với siêu phẩm OPPO Reno15 5G, hứa hẹn mang đến một trải nghiệm vượt trội cho người dùng. Sở hữu thiết kế thanh lịch, camera độ nét cao hỗ trợ quay chụp sắc nét cùng hiệu suất hoạt động mượt mà, thiết bị không chỉ là mộ...' WHERE [ProductName] = N'OPPO Reno15 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 02/2025, Apple giới thiệu mẫu iPhone 16e 128GB - "người em út" đầy tiềm năng của thế hệ iPhone 16 series. Mang trên mình diện mạo trẻ trung, năng động kết hợp cùng những cải tiến công nghệ hiện đại, chiếc điện thoại này hứa hẹn sẽ mang đến ...' WHERE [ProductName] = N'iPhone 16e 128GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào tháng 11/2024, OPPO chính thức giới thiệu mẫu smartphone cao cấp OPPO Reno14 5G (12GB/512GB). Chiếc điện thoại này thu hút người dùng nhờ thiết kế tinh xảo, hệ thống camera xuất sắc, nhiều tính năng tiện ích với hệ thống OPPO AI cùng viên pin...' WHERE [ProductName] = N'OPPO Reno14 5G 12GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 01/2025, Samsung đã chính thức trình làng thế hệ kế nhiệm của dòng S24 Series. Trong đó, mẫu Samsung Galaxy S25 gây ấn tượng mạnh với thiết kế được tinh chỉnh, viền màn hình siêu mỏng, hiệu năng vượt trội cùng những tiện ích độc quyền từ Ga...' WHERE [ProductName] = N'Samsung Galaxy S25 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại iPhone 17e 256GB hứa hẹn là làn gió mới trên thị trường smartphone, thu hút sự chú ý mạnh mẽ từ cộng đồng công nghệ khi được ra mắt. Nổi bật với thiết kế hiện đại, sự nâng cấp về màn hình cùng những tính năng hỗ trợ thông minh từ Apple...' WHERE [ProductName] = N'iPhone 17e 256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại iPhone 15 128GB có thể nói là một mẫu điện thoại được mong chờ nhất trong tháng 09/2023, máy sở hữu một con chip hiệu năng cao, màn hình đẹp cùng khả năng chụp ảnh vô cùng sắc nét, điều này làm cho máy trở thành một cái tên khó có thể ...' WHERE [ProductName] = N'iPhone 15 128GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào tháng 09/2024, hãng công nghệ nổi tiếng Xiaomi đã chính thức giới thiệu dòng điện thoại mới Xiaomi 15T Pro 5G. Mẫu điện thoại này nhanh chóng thu hút sự chú ý khi mang đến diện mạo độc đáo, thiết kế cực kỳ cứng cáp cùng viên pin dung lượng lớ...' WHERE [ProductName] = N'Xiaomi 15T Pro 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung tiếp tục khẳng định đẳng cấp của mình trên thị trường smartphone gập bằng việc ra mắt chiếc Galaxy Z Flip7 FE, một thiết bị mang đến làn gió mới về thiết kế và công nghệ. Không chỉ nổi bật với cơ chế gập vỏ sò sang trọng, máy còn hứa hẹn ...' WHERE [ProductName] = N'Samsung Galaxy Z Flip7 FE 5G 8GB/128GB';
UPDATE [dbo].[Products] SET [Description] = N'Ra mắt vào đầu năm 2025, OPPO Reno15 Pro 5G hứa hẹn sẽ mang đến một làn gió mới trong phân khúc điện thoại cận cao cấp. Với thiết kế mỏng nhẹ đầy tinh tế, hệ thống camera chất lượng cùng hiệu năng mạnh mẽ, đây chắc chắn là chiếc smartphone làm hà...' WHERE [ProductName] = N'OPPO Reno15 Pro 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 09/2024, hãng Xiaomi đã tung ra chiếc điện thoại thông minh cao cấp Xiaomi 15T Pro 5G (12GB/512GB). Đây là bản nâng cấp đáng giá với không gian lưu trữ rộng rãi và vi xử lý mạnh mẽ, cùng loạt các trang bị như camera Leica, màn hình sắc nét ...' WHERE [ProductName] = N'Xiaomi 15T Pro 5G 12GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Motorola chính thức bước vào đường đua smartphone gập với siêu phẩm Moto Razr 60 5G, hứa hẹn mang đến một làn gió mới. Sở hữu thiết kế bản lề giọt nước độc đáo, kết hợp cùng màn hình đôi tiện ích và sạc nhanh siêu tốc, thiết bị này chắc chắn sẽ t...' WHERE [ProductName] = N'Motorola Razr 60 5G 8GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung Galaxy S25 Edge đã chính thức ra mắt, hứa hẹn sẽ "khuấy đảo" thị trường điện thoại cao cấp trong năm 2025. Mẫu smartphone này gây ấn tượng mạnh mẽ với viền siêu mỏng ấn tượng, thiết kế mỏng nhẹ và hiệu năng bứt phá, mở ra những trải nghi...' WHERE [ProductName] = N'Samsung Galaxy S25 Edge 5G 12GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Trong năm 2023 thì Apple cũng đã tung ra các sản phẩm điện thoại thông minh mới mang tên dòng iPhone 15, trong đó nổi bật với phiên bản iPhone 15 Plus 128GB, chiếc máy được trang bị màn hình lớn, camera sắc nét và một hiệu năng vượt trội nhờ chip...' WHERE [ProductName] = N'iPhone 15 Plus 128GB';
UPDATE [dbo].[Products] SET [Description] = N'Với việc ra mắt siêu phẩm Xiaomi 15T Pro 5G (12GB/1TB), Xiaomi tiếp tục khẳng định sự đổi mới của mình trong phân khúc cao cấp. Chiếc smartphone này mang đến một hệ thống camera được nâng cấp vượt bậc, cùng với các thông số ấn tượng như sạc cực n...' WHERE [ProductName] = N'Xiaomi 15T Pro 5G 12GB/1TB';
UPDATE [dbo].[Products] SET [Description] = N'Vào tháng 09/2024, Apple tiếp tục mang đến làn gió mới cho thị trường smartphone với mẫu iPhone 16 128GB. Không chỉ nổi bật ở cụm camera được thiết kế dọc thanh lịch, sản phẩm còn có nút Camera Control hoàn toàn mới tiện lợi. Bên cạnh đó, hiệu nă...' WHERE [ProductName] = N'iPhone 16 128GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào giữa tháng 10/2024, vivo chính thức trình làng mẫu điện thoại cao cấp vivo X300 5G, làm "khuấy đảo" thị trường với thiết kế thời thượng, màn hình lớn, chất lượng sắc nét cùng cụm camera Zeiss vượt trội, hứa hẹn trở thành chiếc điện thoại đáp ...' WHERE [ProductName] = N'vivo X300 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Cuối năm 2024, OPPO chính thức mang đến mẫu điện thoại flagship mới - OPPO Find X8, nhanh chóng thu hút sự chú ý của giới yêu công nghệ. Với thiết kế cụm camera Cosmos Ring đầy khác biệt cùng loạt tính năng AI độc đáo, phiên bản 512 GB này hứa hẹ...' WHERE [ProductName] = N'OPPO Find X8 5G 16GB/512GB Hồng';
UPDATE [dbo].[Products] SET [Description] = N'Samsung Galaxy S24 Ultra 256GB - Mẫu điện thoại thuộc dòng Galaxy S cao cấp được giới thiệu vào tháng 01/2024 với nhiều trang bị hấp dẫn. Điển hình như chip Snapdragon 8 Gen 3 for Galaxy, thiết kế khung Titanium, camera 200 MP và đặc biệt là loạt...' WHERE [ProductName] = N'Samsung Galaxy S24 Ultra 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Nằm trong dòng sản phẩm cao cấp vừa được Samsung trình làng vào tháng 01/2025, Galaxy S25 Plus hứa hẹn làm chao đảo thị trường smartphone với những nâng cấp đầy ấn tượng. Chiếc điện thoại này sở hữu viền màn hình siêu mỏng, hiệu năng vượt trội cù...' WHERE [ProductName] = N'Samsung Galaxy S25 Plus 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Motorola chính thức gia nhập đường đua công nghệ AI với việc ra mắt mẫu smartphone Motorola Signature, gây ấn tượng bởi thiết kế độc đáo và cấu hình mạnh mẽ. Với viên pin bền bỉ, màn hình sắc nét và hiệu suất cao, chiếc điện thoại này hứa hẹn sẽ ...' WHERE [ProductName] = N'Motorola Signature 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Dòng sản phẩm điện thoại gập thông minh của nhà Samsung chào đón thành viên mới mang tên Samsung Galaxy Z Flip7 5G. Nhờ sự kết hợp hoàn hảo giữa diện mạo tinh tế cùng những công nghệ đẳng cấp, hứa hẹn đem đến trải nghiệm tuyệt vời cho mọi nhu cầu...' WHERE [ProductName] = N'Samsung Galaxy Z Flip7 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại thông minh OPPO Find X9 được ra mắt với diện mạo vô cùng thời thượng, cùng với đó là nhiều tính năng độc đáo giúp mang lại trải nghiệm sử dụng tuyệt vời. Với hiệu năng mạnh mẽ và hệ thống camera ấn tượng, chiếc điện thoại OPPO này chắc...' WHERE [ProductName] = N'OPPO Find X9 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 10/2024, thương hiệu điện thoại Xiaomi chính thức ra mắt mẫu điện thoại thông minh cao cấp Xiaomi 17. Mẫu smartphone này nhanh chóng trở thành tâm điểm với thiết kế thời thượng, màn hình sắc nét, cấu hình "khủng" cùng những tính năng nổi bậ...' WHERE [ProductName] = N'Xiaomi 17 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung tiếp tục khẳng định vị thế trong phân khúc điện thoại thông minh cao cấp với việc ra mắt Galaxy S26 5G. Sản phẩm này hứa hẹn sẽ mang đến những trải nghiệm tuyệt vời nhờ sự nâng cấp vượt bậc về cấu hình, tích hợp trí tuệ nhân tạo Galaxy AI...' WHERE [ProductName] = N'Samsung Galaxy S26 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại iPhone 17 hứa hẹn mang đến một sự kết hợp hoàn hảo giữa thiết kế đột phá, cấu hình đỉnh cao và hàng loạt tính năng hiện đại. Không chỉ đơn thuần là công cụ giao tiếp, sản phẩm còn là biểu tượng đẳng cấp dành riêng cho những ai yêu thíc...' WHERE [ProductName] = N'iPhone 17 256GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, Apple đã ra mắt mẫu iPhone Air 256GB, tạo dấu ấn mạnh mẽ trên thị trường smartphone nhờ sự cân bằng hoàn hảo giữa ngoại hình thanh lịch và tính năng hiện đại. Mẫu điện thoại cao cấp này hướng tới những người dùng ưa chuộng sự nhỏ gọn như...' WHERE [ProductName] = N'iPhone Air 256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào 09/2024, hãng Apple tiếp tục tạo điểm nhấn trên thị trường công nghệ bằng việc trình làng chiếc iPhone 16 Plus 128GB. Một phiên bản mang lại kích thước màn hình to, viên pin lớn và đặc biệt giá bán tiết kiệm hơn dòng Pro Max cùng loại, đây ch...' WHERE [ProductName] = N'iPhone 16 Plus 128GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO Find N3 là mẫu điện thoại gập đầu tiên mà OPPO phát hành tại Việt Nam vào tháng 10/2023. Sự hiện diện của nó đã nhanh chóng tạo được sự ấn tượng nhờ vào bản lề bền bỉ, màn hình chất lượng và cấu hình vô cùng mạnh mẽ, hứa hẹn là một bước đột ...' WHERE [ProductName] = N'OPPO Find N3 5G 16GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, Samsung đã giới thiệu Samsung Galaxy S26 Plus - chiếc điện thoại cao cấp hội tụ đầy đủ những công nghệ tiên tiến nhất. Sở hữu thiết kế hiện đại, cấu hình vượt trội cùng hệ thống AI cực kỳ thông minh, máy sẵn sàng đáp ứng mọi nhu cầu từ g...' WHERE [ProductName] = N'Samsung Galaxy S26+ 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Tháng 01/2025, dòng Galaxy S thế hệ mới chính thức xuất hiện, trong đó Samsung Galaxy S25 Ultra vươn lên nổi bật như một biểu tượng của sự tinh tế và quyền năng. Siêu phẩm này đánh dấu sự trở lại với thiết kế sang trọng đầy lôi cuốn, cụm camera m...' WHERE [ProductName] = N'Samsung Galaxy S25 Ultra 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'OPPO Find X8 Pro chính thức gia nhập đường đua flagship vào cuối năm 2024, mang đến sự thay đổi lớn về diện mạo cũng như các tính năng vượt trội. Nổi bật với camera tele kép 50 MP, thiết kế mặt lưng ấn tượng và hiệu năng mạnh mẽ, chiếc điện thoại...' WHERE [ProductName] = N'OPPO Find X8 Pro 5G 16GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Một sự xuất hiện đầy ấn tượng đến từ nhà Táo mang tên điện thoại iPhone 16 Pro Max 256GB ra mắt vào tháng 09/2024. Với sự hiện diện của chip Apple A18 Pro mạnh mẽ, camera chụp ảnh đỉnh cao, tích hợp nút Camera Control mới giúp chiếc iPhone này hứ...' WHERE [ProductName] = N'iPhone 16 Pro Max 256GB';
UPDATE [dbo].[Products] SET [Description] = N'Ngay từ khi mới ra mắt, vivo X300 Pro 5G đã thu hút mọi ánh nhìn với vẻ ngoài cao cấp và các thông số kỹ thuật xuất sắc, hứa hẹn sẽ là một trong những sản phẩm nổi bật nhất trong năm. Từ màn hình sắc nét, cấu hình "khủng", pin siêu trâu cho đến c...' WHERE [ProductName] = N'vivo X300 Pro 5G 16GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung tiếp tục khẳng định sự sáng tạo không giới hạn bằng việc cho ra mắt Galaxy S26 Ultra 5G, một siêu phẩm hứa hẹn sẽ bùng nổ trên thị trường di động cao cấp. Cùng với những cải tiến công nghệ từ màn hình đỉnh cao, camera chuyên nghiệp đến hi...' WHERE [ProductName] = N'Samsung Galaxy S26 Ultra 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Sự xuất hiện của mẫu flagship OPPO Find X9 Pro dự kiến sẽ thiết lập những tiêu chuẩn mới trong ngành công nghiệp di động. Nổi bật với thiết kế siêu mỏng nhẹ nhưng vô cùng chắc chắn, điện thoại được ưu ái trang bị nhiều thông số kỹ thuật hàng đầu,...' WHERE [ProductName] = N'OPPO Find X9 Pro 5G 16GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Điện thoại iPhone 17 Pro 256GB hứa hẹn đem đến cho bạn một trải nghiệm hoàn toàn khác biệt với thiết kế cao cấp, hiệu năng mạnh mẽ vượt bậc và hệ thống camera đỉnh cao. Nhờ những công nghệ tiên tiến, siêu phẩm mới nhất của Apple chắc chắn sẽ làm ...' WHERE [ProductName] = N'iPhone 17 Pro 256GB';
UPDATE [dbo].[Products] SET [Description] = N'Mới đây, Xiaomi đã trình làng Xiaomi 17 Ultra, nhanh chóng thu hút sự chú ý của cộng đồng yêu công nghệ và hứa hẹn sẽ "làm mưa làm gió" trên thị trường smartphone cao cấp. Đây là sự nâng cấp đột phá từ thế hệ tiền nhiệm, kết hợp hiệu năng vượt tr...' WHERE [ProductName] = N'Xiaomi 17 Ultra 5G 16GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Sự hiện diện của iPhone 17 Pro Max 256GB hứa hẹn tạo nên một tiêu chuẩn mới cho dòng điện thoại cao cấp của Apple. Từ chất liệu bền bỉ đến các cải tiến về vi xử lý mạnh mẽ, camera độ phân giải cao và tính năng trí tuệ nhân tạo (Apple Intelligence...' WHERE [ProductName] = N'iPhone 17 Pro Max 256GB';
UPDATE [dbo].[Products] SET [Description] = N'Vào tháng 09/2024, hãng Apple giới thiệu mẫu iPhone 16 Pro 1TB, được đánh giá là một bước tiến đột phá, thiết lập tiêu chuẩn hoàn toàn mới cho dòng điện thoại cao cấp. Siêu phẩm này không chỉ sở hữu thiết kế Titanium sang trọng, cấu hình đỉnh cao...' WHERE [ProductName] = N'iPhone 16 Pro 1TB';
UPDATE [dbo].[Products] SET [Description] = N'Samsung tiếp tục khẳng định vị thế dẫn đầu trên thị trường điện thoại gập thông minh bằng việc trình làng thế hệ mới mang tên Samsung Galaxy Z Fold7 5G. Mẫu máy này hứa hẹn sẽ mang đến những trải nghiệm di động đột phá cho người dùng với sự kết h...' WHERE [ProductName] = N'Samsung Galaxy Z Fold7 5G 12GB/256GB';
UPDATE [dbo].[Products] SET [Description] = N'Sự xuất hiện của HONOR Magic V5 đã gây ấn tượng lớn trong phân khúc điện thoại cao cấp, nhờ sự kết hợp hoàn hảo giữa diện mạo siêu mỏng nhẹ và cấu hình đỉnh cao. Thiết bị mang đến những trải nghiệm di động đột phá với màn hình gập ấn tượng, camera...' WHERE [ProductName] = N'HONOR Magic V5 5G 16GB/512GB';
UPDATE [dbo].[Products] SET [Description] = N'Trong sự kiện gần đây, sự xuất hiện của Xiaomi 17 Ultra Limited Leica đã khiến đông đảo những tín đồ công nghệ và nhiếp ảnh đứng ngồi không yên. Sự kết hợp giữa Xiaomi và thương hiệu nhiếp ảnh Leica không chỉ dừng lại ở tính năng camera, mà còn m...' WHERE [ProductName] = N'Xiaomi 17 Ultra 5G Limited Leica 16GB/1TB';